/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.app;

import android.os.Environment;

public class Constant {
    public static  long ARTICLE_PAGE_SIZE = 10L;
    public static String CACHE_DIR_IMAGE = Environment.getExternalStorageDirectory().getPath() + "/cn.cloudartisan.crius/image";
    public static String CACHE_DIR_VOICE = Environment.getExternalStorageDirectory().getPath() + "/cn.cloudartisan.crius/voice";
    public static  String CHAT_OTHRES_ID = "othersId";
    public static String CHAT_OTHRES_NAME = "othersName";
    public static  String CIM_SERVER_HOST = "cim.farsunset.com";
    public static int CIM_SERVER_PORT = 28888;
    public static  String DOWNLOAD_DIR = Environment.getExternalStorageDirectory().getPath() + "/cn.cloudartisan.crius/download";
    public static   int EMOTION_FACE_SIZE = 24;
    public static String LOG_DIR = Environment.getExternalStorageDirectory().getPath() + "/cn.cloudartisan.crius/log";
    public static long MESSAGE_PAGE_SIZE = 20L;
    public static int RESULT_ZOOM = 11;
    public static String SERVER_URL = "http://developer.yljr888.com";
    public static String SYSTEM = "system";
    

}
