/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.app;

import android.content.SharedPreferences;
import cn.cloudartisan.crius.bean.User;

public class Global {
    static final String KEY_USER_ACCOUNT = "KEY_USER_ACCOUNT";
    static final String KEY_USER_GENDER = "KEY_USER_GENDER";
    static final String KEY_USER_ICON = "KEY_USER_ICON";
    static final String KEY_USER_LATITUDE = "KEY_USER_LATITUDE";
    static final String KEY_USER_LOCATION = "KEY_USER_LOCATION";
    static final String KEY_USER_LONGITUDE = "KEY_USER_LONGITUDE";
    static final String KEY_USER_MOTTO = "KEY_USER_MOTTO";
    static final String KEY_USER_NAME = "KEY_USER_NAME";
    static final String KEY_USER_PASSWORD = "KEY_USER_PASSWORD";
    static final String MODEL_KEY = "CURRENT_USER";

    
    public static User getCurrentUser() {

         User   user = new User();

        SharedPreferences sp = LvxinApplication.getInstance().getSharedPreferences(MODEL_KEY, 0x0);
        user.setAccount(sp.getString(KEY_USER_ACCOUNT, null)); ;
        user.setPassword(sp.getString(KEY_USER_PASSWORD, null));
        user.setName(sp.getString(KEY_USER_NAME, null));
        user.setGender(sp.getString(KEY_USER_GENDER,null));// = sp.getString("KEY_USER_GENDER", null);
        user.setMotto(sp.getString(KEY_USER_MOTTO,null)); //= sp.getString("KEY_USER_MOTTO", null);
        user.setLongitude(sp.getString(KEY_USER_LONGITUDE,null)); //= sp.getString("KEY_USER_LONGITUDE", null);
        user.setLatitude(sp.getString(KEY_USER_LATITUDE,null)); //= sp.getString("KEY_USER_LATITUDE", null);
        user.setLocation(sp.getString(KEY_USER_LOCATION,null));// = sp.getString("KEY_USER_LOCATION", null);

        return user;
    }
    
    public static void setCurrentUser(User user) {
        if(user != null) {
           // user = u;
            SharedPreferences sp = LvxinApplication.getInstance().getSharedPreferences(MODEL_KEY, 0x0);
            SharedPreferences.Editor  editor=sp.edit();
            editor.putString(KEY_USER_ACCOUNT, user.getAccount());
            editor.putString(KEY_USER_PASSWORD, user.getPassword());
            editor.putString(KEY_USER_NAME, user.getName());
            editor.putString(KEY_USER_GENDER, user.getGender());
            editor.putString(KEY_USER_MOTTO, user.getMotto());
            editor.putString(KEY_USER_LONGITUDE, user.getLongitude());
            editor.putString(KEY_USER_LATITUDE, user.getLatitude());
            editor.putString(KEY_USER_LOCATION, user.getLocation());
            editor.commit();
        }
    }
    
    public static void removePassword() {
        SharedPreferences sp = LvxinApplication.getInstance().getSharedPreferences(MODEL_KEY, 0x0);
        sp.edit().remove(KEY_USER_PASSWORD).commit();
    }
}
