/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.app;

import android.media.MediaPlayer;
import java.io.File;

public class GlobalVoicePlayer implements MediaPlayer.OnCompletionListener {
    MediaPlayer mMediaPlayer;
    GlobalVoicePlayer.OnPlayListener onPlayListener;
    static GlobalVoicePlayer player;
    String token;
    
    private GlobalVoicePlayer() {
        mMediaPlayer = new MediaPlayer();
        mMediaPlayer.setOnCompletionListener(this);
    }
    
    public static GlobalVoicePlayer getPlayer() {
        if(player == null) {
            player = new GlobalVoicePlayer();
        }
        return player;
    }
    
    public void start(File file, GlobalVoicePlayer.OnPlayListener l) {
        if(token != null) {
            if((isPlaying()) && (file.getAbsolutePath().equals(token))) {
                stop();
                return;
            }
            if((isPlaying()) && (!file.getAbsolutePath().equals(token)) && (onPlayListener != null)) {
                onPlayListener.onVoiceStop();
            }
        }
        onPlayListener = l;
        token = file.getAbsolutePath();
        start();
    }
    
    private void start() {
        try {
            if(isPlaying()) {
                mMediaPlayer.stop();
                mMediaPlayer.release();
            }
            mMediaPlayer = new MediaPlayer();
            mMediaPlayer.setOnCompletionListener(this);
            mMediaPlayer.reset();
            mMediaPlayer.setDataSource(token);
            mMediaPlayer.prepare();
            mMediaPlayer.start();
            return;
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void stop() {
        if(isPlaying()) {
            mMediaPlayer.stop();
            mMediaPlayer.release();
        }
        mMediaPlayer = null;
        if(onPlayListener != null) {
            onPlayListener.onVoiceStop();
            onPlayListener = null;
        }
    }
    
    private boolean isPlaying() {
        try {
            return mMediaPlayer.isPlaying();
        } catch(Exception localException1) {
        }
        return false;
    }
    
    public void onSwitchMode() {
        if(token != null) {
            if(isPlaying()) {
                mMediaPlayer.stop();
                mMediaPlayer.release();
            }
            start();
        }
    }
    
    public void pause() {
        if(token != null) {
            mMediaPlayer.pause();
        }
    }
    
    public void onCompletion(MediaPlayer mediaplayer) {
        if(onPlayListener != null) {
            onPlayListener.onCompletion(mediaplayer);
        }
        token = null;
    }

    public interface OnPlayListener
    {
         void onCompletion(MediaPlayer paramMediaPlayer);

        void onVoiceStop();
    }
}
