/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.setting;

import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.view.View;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.ui.base.BaseActivity;

public class AboutActivity extends BaseActivity {
    
    public void initComponents() {
        setDisplayHomeAsUpEnabled(true);
        PackageManager packageManager = getPackageManager();
        try {
            PackageInfo packInfo = packageManager.getPackageInfo(getPackageName(), 0);
            String version = packInfo.versionName;
            ((TextView)findViewById(R.id.version)).setText(version);
        } catch(PackageManager.NameNotFoundException ex) {
        }
        findViewById(R.id.item_name).setOnClickListener(this);
        findViewById(R.id.item_qq).setOnClickListener(this);
        findViewById(R.id.item_weixin).setOnClickListener(this);
    }
    
    public void onClick(View v) {
    }
    
    public int getConentLayout() {
        return R.layout.activity_about;
    }
    
    public int getActionBarTitle() {
        return R.string.common_about;
    }
}
