/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.setting;

import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.component.WebImageView;
import cn.cloudartisan.crius.ui.trend.MyCircleHomeActivity;
import cn.cloudartisan.crius.util.FileURLBuilder;
import com.nostra13.universalimageloader.core.ImageLoader;

public class UserCenterFragment extends Fragment implements View.OnClickListener {
    WebImageView icon;
    User user;
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        user = Global.getCurrentUser();
    }
    
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.activity_user_center, container, false);
    }
    
    public void onViewCreated(View view, Bundle savedInstanceState) {
        view.findViewById(R.id.iconSwicth).setOnClickListener(this);
        view.findViewById(R.id.item_album).setOnClickListener(this);
        view.findViewById(R.id.item_setting).setOnClickListener(this);
        icon = (WebImageView)view.findViewById(R.id.icon);
        icon.load(FileURLBuilder.getUserIconUrl(user.getAccount()));
        TextView name = (TextView)view.findViewById(R.id.username);
        TextView account = (TextView)view.findViewById(R.id.account);
        name.setText(user.getName());
        account.setText(user.getAccount());
    }
    
    public void onResume() {
        super.onResume();
        user = Global.getCurrentUser();
        String url = FileURLBuilder.getUserIconUrl(user.getAccount());
        ImageLoader.getInstance().getMemoryCache().remove(url);
        icon.load(url);
        TextView name = (TextView)getView().findViewById(R.id.username);
        TextView account = (TextView)getView().findViewById(R.id.account);
        name.setText(user.getName());
        account.setText(user.getAccount());
    }
    
    public void onClick(View v) {
        switch(v.getId()) {
            case R.id.iconSwicth:
            {
                Intent intentFromGallery = new Intent();
                intentFromGallery.setClass(getActivity(), ProfileEditActivity.class);
                startActivityForResult(intentFromGallery, 0x9);
                return;
            }
            case R.id.item_album:
            {
                Intent modiftPasswordIntent = new Intent(getActivity(), MyCircleHomeActivity.class);
                startActivity(modiftPasswordIntent);
                return;
            }
            case R.id.item_setting:
            {
                Intent modiftMottoIntent = new Intent(getActivity(), SettingCenterActivity.class);
                startActivity(modiftMottoIntent);
                break;
            }
        }
    }
}
