/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.util;

import android.view.View;
import cn.cloudartisan.crius.app.LvxinApplication;
import android.view.animation.AnimationUtils;
import android.view.animation.Animation;

public class AnimationTools {
    
    public static void start(int aid, View view, AnimationTools.OnAnimationListener listener) {
        Animation a = AnimationUtils.loadAnimation(LvxinApplication.getInstance(), aid);
        start(a, view, listener);
    }
    
    public static void start(Animation a, final View view, final AnimationTools.OnAnimationListener listener) {
        a.setAnimationListener(new Animation.AnimationListener() {
            

            public void onAnimationEnd(Animation animation) {
                listener.onAnimationEnd(view);
            }
            
            public void onAnimationRepeat(Animation animation) {
            }
            
            public void onAnimationStart(Animation animation) {
                listener.onAnimationStart(view);
            }
        });
        view.startAnimation(a);
    }
    public  interface OnAnimationListener
    {
        void onAnimationEnd(View paramView);

        void onAnimationStart(View paramView);
    }
}
