/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.util;

import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import android.graphics.Bitmap;
import java.io.FileOutputStream;

import org.apache.commons.io.IOUtils;

public class FileUtil {
    
    public static File creatSDFile(String fileName) {
        File file = new File(fileName);
        try {
            file.createNewFile();
            return file;
        } catch(IOException localIOException1) {
        }
        return file;
    }
    
    public static File creatSDDir(String dirName) {
        File dir = new File(dirName);
        dir.mkdirs();
        return dir;
    }
    
    public static boolean isFileExist(String fileName) {
        try {
            File file = new File(fileName);
            return file.exists();
        } catch(Exception localException1) {
        }
        return false;
    }
    
    public static File saveFile(File file, Bitmap photo) {
        FileOutputStream fOut = null;
        try {
            if(!file.exists()) {
                file.createNewFile();
            }
             fOut = new FileOutputStream(file);
        } catch(Exception e) {
            e.printStackTrace();
        }
        photo.compress(Bitmap.CompressFormat.PNG, 0x64, fOut);
        IOUtils.closeQuietly(fOut);
        return file;
    }
    
    public static String getSizeName(long size) {
        DecimalFormat format = new DecimalFormat("0.00");
        if(size < 0x400) {
            return "B";
        }
        if((size >= 0x400) && (size < 0x100000)) {
            return "KB";
        }
        return "M";
    }
}
