/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.util;

import java.util.Comparator;
import cn.cloudartisan.crius.bean.Comment;

public class PublishTimeAscComparator implements Comparator<Comment>{
    
    public int compare(Comment arg0, Comment arg1) {
        return arg0.timestamp.compareTo(arg1.timestamp);
    }
}
