/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.util;

import java.util.Comparator;
import cn.cloudartisan.crius.bean.PublicMenu;

public class PubMenuAscComparator implements Comparator<PublicMenu> {
    
    public int compare(PublicMenu arg0, PublicMenu arg1) {
        return (arg0.sort - arg1.sort);
    }
}
