/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.util;

import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;

public class ShakeListener implements SensorEventListener {
    private static final int SPEED_SHRESHOLD = 5000;
    private static final int UPTATE_INTERVAL_TIME = 70;
    private long lastUpdateTime;
    private float lastX;
    private float lastY;
    private float lastZ;
    private Context mContext;
    private ShakeListener.OnShakeListener onShakeListener;
    private Sensor sensor;
    private SensorManager sensorManager;
    
    public ShakeListener(Context c) {
        mContext = c;
        sensorManager = (SensorManager)mContext.getSystemService(Context.SENSOR_SERVICE);
        if(sensorManager != null) {
            sensor = sensorManager.getDefaultSensor(1);
        }
    }
    
    public void unregisterListener() {

        sensorManager.unregisterListener(this);
    }
    
    public void registerListener() {
        if((sensor != null) && (sensorManager != null)) {
            sensorManager.registerListener(this, sensor, 0x1);
        }
    }
    
    public void setOnShakeListener(ShakeListener.OnShakeListener listener) {
        onShakeListener = listener;
    }

    public void onSensorChanged(SensorEvent event) {

        long var8 = System.currentTimeMillis();
        long var10 = var8 - this.lastUpdateTime;
        if(var10 >= 70L) {

            this.lastUpdateTime = var8;
            float var2 = event.values[0];
            float var3 = event.values[1];
            float var4 = event.values[2];
            float var5 = var2 - this.lastX;
            float var6 = var3 - this.lastY;
            float var7 = var4 - this.lastZ;
            this.lastX = var2;
            this.lastY = var3;
            this.lastZ = var4;
            if(Math.sqrt((double)(var5 * var5 + var6 * var6 + var7 * var7)) / (double)var10 * 10000.0D >= 5000.0D) {

                this.onShakeListener.onShake();

                return;
            }
        }

    }
    
    public void onAccuracyChanged(Sensor sensor, int accuracy) {
    }
    public  interface OnShakeListener
    {
       void onShake();
    }
}
