/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.TextView;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.Comment;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.component.WebImageView;
import cn.cloudartisan.crius.util.AppTools;
import cn.cloudartisan.crius.util.FileURLBuilder;

import java.util.ArrayList;
import java.util.List;

public class CircleMessageAdapter extends BaseAdapter {
    protected Context context;
    protected List<Message> list=new ArrayList<>();
    
    public CircleMessageAdapter(Context c, List<Message> list) {
        context = c;
        this.list = list;
    }
    
    public int getCount() {
        return list.size();
    }
    
    public Message getItem(int position) {
        return (Message)list.get(position);
    }
    
    public long getItemId(int position) {
        return 0;
    }
    
    public View getView(int index, View friendItemView, ViewGroup parent) {
        Comment comment =JSON.parseObject(getItem(index).content, Comment.class);
        JSONObject json = JSON.parseObject(comment.content);
        CircleMessageAdapter.ViewHolder viewHolder =friendItemView==null?  new CircleMessageAdapter.ViewHolder():(CircleMessageAdapter.ViewHolder)friendItemView.getTag();
        if(friendItemView == null) {
            friendItemView = LayoutInflater.from(context).inflate(R.layout.item_circle_message, null);

            viewHolder.name = (TextView) friendItemView.findViewById(R.id.name);
            viewHolder.icon = (WebImageView) friendItemView.findViewById(R.id.icon);
            viewHolder.content = (TextView) friendItemView.findViewById(R.id.content);
            viewHolder.time = (TextView) friendItemView.findViewById(R.id.time);
            friendItemView.setTag(viewHolder);
        }
        viewHolder.icon.load(FileURLBuilder.getUserIconUrl(comment.account), R.drawable.icon_head_default);
        viewHolder.name.setText(json.getString("name"));
        viewHolder.content.setText(json.getString("content"));
        viewHolder.time.setText(AppTools.howTimeAgo(context, Long.valueOf(comment.timestamp).longValue()));
        return friendItemView;
    }
    
    class ViewHolder {
        TextView content;
        WebImageView icon;
        TextView name;
        TextView time;
    }
}
