/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.content.Context;
import android.content.Intent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.TypeReference;
import com.alibaba.fastjson.parser.Feature;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.Article;
import cn.cloudartisan.crius.bean.SNSImage;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.component.SNSImageView;
import cn.cloudartisan.crius.ui.chat.MMWebViewActivity;
import cn.cloudartisan.crius.util.AppTools;
import cn.cloudartisan.crius.util.StringUtils;

import java.util.ArrayList;
import java.util.List;

public class MyCircleListViewAdapter extends BaseAdapter {
    protected Context context;
    protected List<Article> list =new ArrayList<>();
    User self;
    
    public MyCircleListViewAdapter(Context c, List<Article> list) {
        context = c;
        this.list = list;
        self = Global.getCurrentUser();
    }
    
    public int getCount() {
        return list.size();
    }
    
    public Article getItem(int position) {
        return (Article)list.get(position);
    }
    
    public long getItemId(int position) {
        return 0;
    }

    public View getView(int var1, View var2, ViewGroup var3) {
        Article var5 = this.getItem(var1);

        MyCircleListViewAdapter.ViewHolder var7;
        if(var2 == null) {
            var2 = LayoutInflater.from(this.context).inflate(R.layout.sns_myarticle_item, null);
            var7 = new MyCircleListViewAdapter.ViewHolder();
            var7.day = (TextView)var2.findViewById(R.id.day);
            var7.text = (TextView)var2.findViewById(R.id.text);
            var7.month = (TextView)var2.findViewById(R.id.month);
            var7.singleImageView = (SNSImageView)var2.findViewById(R.id.singleImageView);
            var7.rootImageViewPanel = (LinearLayout)var2.findViewById(R.id.rootImageViewPanel);
            var7.linkTitle = (TextView)var2.findViewById(R.id.linkTitle);
            var7.linkPanel = var2.findViewById(R.id.linkPanel);
            var2.setTag(var7);
        } else {
            var7 = (MyCircleListViewAdapter.ViewHolder)var2.getTag();
        }

        JSONObject var6 = JSON.parseObject(var5.content);
        if(StringUtils.isNotEmpty(var6.getString("content"))) {
            var7.text.setVisibility(View.VISIBLE);
            var7.text.setText(var6.getString("content"));
        } else {
            var7.text.setVisibility(View.GONE);
        }

        var7.month.setText(AppTools.getMonth(Long.valueOf(var5.timestamp).longValue()) + "\u6708");
        var7.day.setText(AppTools.getDay(Long.valueOf(var5.timestamp).longValue()));
        if(!StringUtils.isEmpty(var5.thumbnail)) {
            List var9 = (List)JSON.parseObject(var5.thumbnail, (new TypeReference() {
            }).getType(), new Feature[0]);
            if(var9.size() == 1) {
                var7.singleImageView.setVisibility(View.VISIBLE);
                var7.singleImageView.display(var5, (SNSImage)var9.get(0), ((SNSImage)var9.get(0)).ow, ((SNSImage)var9.get(0)).oh);
                var7.rootImageViewPanel.setVisibility(View.GONE);
            } else {
                var7.singleImageView.setVisibility(View.GONE);
                var7.rootImageViewPanel.setVisibility(View.VISIBLE);

                int var4;
                for(var1 = 0; var1 < 2; ++var1) {
                    var7.rootImageViewPanel.getChildAt(var1).setVisibility(View.GONE);

                    for(var4 = var1 * 2; var4 < (var1 + 1) * 2; ++var4) {
                        ((LinearLayout)var7.rootImageViewPanel.getChildAt(var1)).getChildAt(var4 - var1 * 2).setVisibility(View.GONE);
                    }
                }

                for(var1 = 0; var1 < (var9.size() - 1) / 2 + 1 && var1 < 2; ++var1) {
                    var7.rootImageViewPanel.getChildAt(var1).setVisibility(View.VISIBLE);

                    for(var4 = var1 * 2; var4 < var9.size() && var4 < (var1 + 1) * 2; ++var4) {
                        ((LinearLayout)var7.rootImageViewPanel.getChildAt(var1)).getChildAt(var4 - var1 * 2).setVisibility(View.VISIBLE);
                        ((SNSImageView)((LinearLayout)var7.rootImageViewPanel.getChildAt(var1)).getChildAt(var4 - var1 * 2)).display(var5, (SNSImage)var9.get(var4));
                    }
                }
            }
        } else {
            var7.rootImageViewPanel.setVisibility(View.GONE);
            var7.singleImageView.setVisibility(View.GONE);
        }

        if(var5.type.equals("1")) {
            final JSONObject var8 = JSON.parseObject(var5.content).getJSONObject("link");
            var7.linkPanel.setVisibility(View.VISIBLE);
            var7.linkPanel.setOnClickListener(new View.OnClickListener() {
                public void onClick(View var1) {
                    Intent var2 = new Intent(MyCircleListViewAdapter.this.context, MMWebViewActivity.class);
                    var2.putExtra("url", var8.getString("link"));
                    MyCircleListViewAdapter.this.context.startActivity(var2);
                }
            });
            var7.linkTitle.setText(var8.getString("title"));
            return var2;
        } else {
            var7.linkPanel.setVisibility(View.GONE);
            return var2;
        }
    }

    class ViewHolder {
        TextView day;
        View linkPanel;
        TextView linkTitle;
        TextView month;
        LinearLayout rootImageViewPanel;
        SNSImageView singleImageView;
        TextView text;
    }
}
