/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.Friend;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.component.WebImageView;
import cn.cloudartisan.crius.util.AppTools;
import cn.cloudartisan.crius.util.DistanceAscComparator;
import cn.cloudartisan.crius.util.FileURLBuilder;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class NearbyListViewAdapter extends BaseAdapter {
    protected Context context;
    protected List<Friend> list =new ArrayList<>();
    User self;
    
    public NearbyListViewAdapter(Context c, List<Friend> list) {
        context = c;
        this.list = list;
        self = Global.getCurrentUser();
    }
    
    public int getCount() {
        return list.size();
    }
    
    public Friend getItem(int position) {
        return (Friend)list.get(position);
    }
    
    public long getItemId(int position) {
        return 0x0;
    }
    
    public void notifyDataSetChanged() {
        Collections.sort(list, new DistanceAscComparator(self));
        super.notifyDataSetChanged();
    }
    
    public View getView(int index, View friendItemView, ViewGroup parent) {
        Friend target = getItem(index);
        NearbyListViewAdapter.ViewHolder viewHolder=null;
        if(friendItemView == null) {
            friendItemView = LayoutInflater.from(context).inflate(R.layout.item_nearby_user, null);
            viewHolder = new NearbyListViewAdapter.ViewHolder();
            viewHolder.icon = (WebImageView)friendItemView.findViewById(R.id.icon);
            viewHolder.username = (TextView)friendItemView.findViewById(R.id.username);
            viewHolder.gender = (ImageView)friendItemView.findViewById(R.id.gender);
            viewHolder.distance = (TextView)friendItemView.findViewById(R.id.distance);
            viewHolder.location = (TextView)friendItemView.findViewById(R.id.location);
            friendItemView.setTag(viewHolder);
        } else {
            viewHolder = (NearbyListViewAdapter.ViewHolder)friendItemView.getTag();
        }
        viewHolder.gender.setVisibility(View.GONE);
        viewHolder.icon.load(FileURLBuilder.getUserIconUrl(target.account), R.drawable.icon_head_default);
        viewHolder.username.setText(target.name);
        if((self.getLongitude() == null) || (self.getLatitude() == null)) {
            viewHolder.distance.setText(R.string.tip_unknow_distance);
        } else {
            viewHolder.distance.setText(AppTools.transformDistance(Double.parseDouble(self.getLongitude()), Double.parseDouble(self.getLatitude()), Double.parseDouble(target.longitude), Double.parseDouble(target.latitude)));
        }
        if((target.location == null) || ("null".equals(target.location))) {
            viewHolder.location.setText(R.string.tip_unknow_location);
        } else {
            viewHolder.location.setText(target.location);
        }
        if("0".equals(target.gender)) {
            viewHolder.gender.setImageResource(R.drawable.icon_lady);
            viewHolder.gender.setVisibility(View.VISIBLE);
        }
        if("1".equals(target.gender)) {
            viewHolder.gender.setImageResource(R.drawable.icon_man);
            viewHolder.gender.setVisibility(View.VISIBLE);
        }
        return friendItemView;
    }
    
    class ViewHolder {
        TextView distance;
        ImageView gender;
        WebImageView icon;
        TextView location;
        TextView username;
    }
}
