/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.SNSImage;
import cn.cloudartisan.crius.component.CustomGridView;
import cn.cloudartisan.crius.component.WebImageView;

import java.util.ArrayList;
import java.util.List;

public class PhotoGridViewAdapter extends BaseAdapter {
    protected Context context;
    protected List<SNSImage> list =new ArrayList<>();
    
    public PhotoGridViewAdapter(Context c, List<SNSImage> list) {
        context = c;
        this.list = list;
    }
    
    public int getCount() {
        return list.size();
    }
    
    public SNSImage getItem(int position) {
        return list.get(position);
    }
    
    public long getItemId(int position) {
        return 0;
    }
    
    public View getView(int paramInt, View paramView, ViewGroup paramViewGroup) {
        if(paramViewGroup instanceof CustomGridView && ((CustomGridView)paramViewGroup).measured()) {
            SNSImage var4 = this.getItem(paramInt);
            View var5 = paramView;
            if(paramView == null) {
                var5 = LayoutInflater.from(this.context).inflate(R.layout.item_grid_photo,null);
            }

            if(var4 == null) {
                ((WebImageView)var5.findViewById(R.id.photo)).setImageResource(R.drawable.addphoto_button);
                return var5;
            } else {
                ((WebImageView)var5.findViewById(R.id.photo)).loadLocale(var4.thumbnail);
                return var5;
            }
        } else {
            return LayoutInflater.from(this.context).inflate(R.layout.item_grid_photo, (ViewGroup)null);
        }
        /*if (((paramViewGroup instanceof CustomGridView)) && (((CustomGridView)paramViewGroup).measured()))
        {
            SNSImage localSNSImage = getItem(paramInt);
            View localView = paramView;
            if (localView == null) {
                localView = LayoutInflater.from(this.context).inflate(R.layout.item_grid_photo, null);
            }
            if (localSNSImage == null)
            {
                ((WebImageView)paramViewGroup.findViewById(R.id.photo)).setImageResource(R.drawable.addphoto_button);
                return paramViewGroup;
            }
            ((WebImageView)paramViewGroup.findViewById(R.id.photo)).loadLocale(localSNSImage.thumbnail);
            return paramViewGroup;
        }
        return LayoutInflater.from(this.context).inflate(R.layout.item_grid_photo, null);*/
    }
}
