/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.PublicAccount;
import cn.cloudartisan.crius.component.WebImageView;
import cn.cloudartisan.crius.util.FileURLBuilder;

import java.util.ArrayList;
import java.util.List;

public class PubAccountListViewAdapter extends BaseAdapter {
    protected Context context;
    protected List<PublicAccount> list =new ArrayList<>();
    
    public PubAccountListViewAdapter(Context c, List<PublicAccount> list) {
        context = c;
        this.list = list;
    }
    
    public int getCount() {
        return list.size();
    }
    
    public PublicAccount getItem(int position) {
        return list.get(position);
    }
    
    public long getItemId(int position) {
        return 0x0;
    }
    
    public View getView(int position, View convertView, ViewGroup parent) {
        PublicAccount target = getItem(position);
        convertView = LayoutInflater.from(context).inflate(R.layout.item_contact_pubaccount, null);
        TextView name = (TextView)convertView.findViewById(R.id.name);
        name.setText(target.name);
        ( (WebImageView)convertView.findViewById(R.id.icon)).load(FileURLBuilder.getPubAccountLogoUrl(target.account), R.drawable.icon_contact_public);
        return convertView;
    }
}
