/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.ShakeRecord;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.component.WebImageView;

import java.util.ArrayList;
import java.util.List;

public class ShakeRecordListViewAdapter extends BaseAdapter {
    protected Context context;
    String creator;
    protected List<ShakeRecord> list =new ArrayList<>();
    User self;
    
    public ShakeRecordListViewAdapter(Context c, List<ShakeRecord> list) {
        context = c;
        this.list = list;
        self = Global.getCurrentUser();
    }
    
    public void remove(ShakeRecord target) {
        list.remove(target);
        notifyDataSetChanged();
    }
    
    public int getCount() {
        return list.size();
    }
    
    public ShakeRecord getItem(int position) {
        return list.get(position);
    }
    
    public long getItemId(int position) {
        return 0x0;
    }
    
    public View getView(int index, View itemView, ViewGroup parent) {
        ShakeRecord target = getItem(index);
        if(itemView == null) {
            itemView = LayoutInflater.from(context).inflate(R.layout.item_shake_record, null);
        }
        ((TextView)itemView.findViewById(R.id.username)).setText("获得【"+target.gender+"】"+target.name);
        /*if((target.longitude != null) || (target.latitude != null)) {
            ((TextView)itemView.findViewById(R.id.location)).setText(AppTools.transformDistance(Double.parseDouble(self.getLongitude()), Double.parseDouble(self.getLatitude()), Double.parseDouble(target.longitude), Double.parseDouble(target.latitude)));
        }*/
    /*    if("0".equals(target.gender)) {
            ( (ImageView)itemView.findViewById(R.id.gender)).setImageResource(R.drawable.icon_lady);
            (itemView.findViewById(R.id.gender)).setVisibility(View.VISIBLE);
        }
        if("1".equals(target.gender)) {
            ((ImageView)itemView.findViewById(R.id.gender)).setImageResource(R.drawable.icon_man);
            (itemView.findViewById(R.id.gender)).setVisibility(View.VISIBLE);
        }*/
        ((WebImageView)itemView.findViewById(R.id.icon)).displayResouce(R.drawable.corn);//.load(FileURLBuilder.getUserIconUrl(target.account), R.drawable.icon_head_default);
        return itemView;
    }
}
