/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.adapter;

import android.support.v4.view.PagerAdapter;
import android.support.v4.view.ViewPager;
import android.view.View;

import java.util.ArrayList;
import java.util.List;

public class ViewPaperAdapter extends PagerAdapter {
    List<View> pageViews =new ArrayList<>();
    
    public ViewPaperAdapter(List<View> pageViews) {
        this.pageViews = pageViews;
    }
    
    public int getCount() {
        return pageViews.size();
    }
    
    public boolean isViewFromObject(View arg0, Object arg1) {
        return (arg0 == arg1);
    }
    
    public int getItemPosition(Object object) {
        return super.getItemPosition(object);
    }

    public void destroyItem(View var1, int var2, Object var3) {
        ((ViewPager)var1).removeView(this.pageViews.get(var2));
    }
    public Object instantiateItem(View var1, int var2) {
        ((ViewPager)var1).addView(this.pageViews.get(var2));
        return this.pageViews.get(var2);
    }


}
