/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.request;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.bean.MessageItemSource;
import cn.cloudartisan.crius.bean.SystemMsg;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.network.HttpAPIRequester;
import cn.cloudartisan.crius.ui.base.BaseActivity;

import java.util.HashMap;

public abstract class RequestHandler {
    public HashMap<String, Object> apiParams;
    BaseActivity context;
    Message message;
    HttpAPIRequester requester;
    User self;
    
    public abstract MessageItemSource decodeMessageSource();
    
    
    public abstract CharSequence getDescription();
    
    
    public abstract CharSequence getMessage();
    
    
    public abstract String getTitle();
    
    
    public abstract void handleAgree();
    
    
    public abstract void handleRefuse();
    
    
    public void setContext(BaseActivity context) {
        context = context;
        self = Global.getCurrentUser();
    }
    
    public void setMessage(Message msg) {
        message = msg;
    }
    
    public void handleIgnore() {
        JSONObject json = JSON.parseObject(message.content);
        json.put(SystemMsg.HANDLE_RESULT, SystemMsg.RESULT_IGNORE);
        message.content = json.toJSONString();
        MessageDBManager.getManager().modifyMsgContent(message);
        context.showToast(context.getString(R.string.tip_handle_succeed));
        context.finish();
    }
}
