/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.request;

import android.graphics.Color;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.text.style.StyleSpan;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.TypeReference;
import cn.cloudartisan.crius.client.constant.CIMConstant;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.*;
import cn.cloudartisan.crius.db.GroupDBManager;
import cn.cloudartisan.crius.db.GroupMemberDBManager;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.message.parser.MessageParserFactory;
import cn.cloudartisan.crius.network.HttpAPIRequester;
import cn.cloudartisan.crius.network.HttpAPIResponser;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Type102RequestHandler extends RequestHandler implements HttpAPIResponser {
    
    public Type102RequestHandler() {
        requester = new HttpAPIRequester(this);
    }
    
    public CharSequence getMessage() {
        JSONObject json = JSON.parseObject(message.content);
        StringBuffer buffer = new StringBuffer();
        Group target = GroupDBManager.getManager().queryGroup(json.getString("targetGroupId"));
        buffer.append(context.getString(R.string.tip_request_joingroup, json.getString("sourceName"), target.name));
        SpannableString text = new SpannableString(buffer.toString());
        text.setSpan(new ForegroundColorSpan(Color.parseColor("#3C568B")), 0x0, json.getString("sourceName").length(), 0x21);
        text.setSpan(new StyleSpan(0x1), 0x0, json.getString("sourceName").length(), 0x21);
        return text;
    }
    
    public String getTitle() {
        return "\u5165\u7fa4\u7533\u8bf7";
    }
    
    public MessageItemSource decodeMessageSource() {
        JSONObject json = JSON.parseObject(message.content);
        Friend friend = new Friend();
        friend.account = json.getString("sourceAccount");
        friend.name = json.getString("sourceName");
        return friend;
    }
    
    public void handleRefuse() {
        JSONObject json = JSON.parseObject(message.content);
        apiParams.put("content", context.getString(R.string.tip_refuse_joingroup,
               self.getName(), json.getString("targetGroupName")));
        apiParams.put("receiver", json.getString("sourceAccount"));
        apiParams.put("type", "2");
        HttpAPIRequester.execute(apiParams, URLConstant.MESSAGE_SEND_URL);
        json.put(SystemMsg.HANDLE_RESULT, SystemMsg.RESULT_REFUSE);
        message.content = json.toJSONString();
        MessageDBManager.getManager().modifyMsgContent(message);
        context.showToast(context.getString(R.string.tip_handle_succeed));
        context.finish();
    }
    
    public void handleAgree() {
        requester.execute(new TypeReference<Type102RequestHandler>() { }.getType(), null, URLConstant.GROUPMEMBER_ADD_URL);
    }
    
    public CharSequence getDescription() {
        JSONObject json = JSON.parseObject(message.content);
        return context.getString(R.string.tip_request_verify, json.getString("requestMsg"));
    }
    
    public void onSuccess(Object data, List list, Page page, String code, String url) {
        context.hideProgressDialog();
        if(CIMConstant.ReturnCode.CODE_200.equals(code)) {
            JSONObject json = JSON.parseObject(message.content);
            MessageDBManager.getManager().batchModifyAgree(json.getString("sourceAccount"), message.type);
            context.showToast(context.getString(R.string.tip_handle_succeed));
            Message newMsg = new Message();
            newMsg.receiver = json.getString("sourceAccount");
            HashMap<String, Object> inputData = new HashMap<String, Object>();
            inputData.put("user", self);
            inputData.put("message", newMsg);
            Group target = GroupDBManager.getManager().queryGroup(json.getString("targetGroupId"));
            inputData.put("group", target);
            newMsg.type = "103";
            MessageParserFactory.getFactory().getMessageParser(newMsg.type).encodeContent(inputData);
            apiParams.clear();
            GroupMember member = new GroupMember();
            member.groupId = target.groupId;
            member.account = newMsg.receiver;
            member.gid = String.valueOf(System.currentTimeMillis());
            member.host = "0";
            GroupMemberDBManager.getManager().saveMember(member);
            HashMap<String, Object> type103Params = new HashMap<String, Object>();
            type103Params.put("content", newMsg.content);
            type103Params.put("sender", "system");
            type103Params.put("receiver", newMsg.receiver);
            type103Params.put("type", newMsg.type);
            HttpAPIRequester.execute(type103Params, URLConstant.MESSAGE_SEND_URL);
            context.finish();
        }
    }
    
    public void onFailed(Exception e) {
        context.hideProgressDialog();
    }
    
    public Map getRequestParams(String code) {
        JSONObject json = JSON.parseObject(message.content);
        apiParams.put("groupId", json.getString("targetGroupId"));
        apiParams.put("account", json.getString("sourceAccount"));
        return apiParams;
    }
    
    public void onRequest() {
        context.showProgressDialog(context.getString(R.string.tip_loading, new Object[] {context.getString(R.string.common_handle)}));
    }
}
