/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.base;

import android.net.NetworkInfo;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.View;
import cn.cloudartisan.crius.client.android.CIMEventListener;
import cn.cloudartisan.crius.client.android.CIMListenerManager;
import cn.cloudartisan.crius.client.model.Message;
import cn.cloudartisan.crius.client.model.ReplyBody;
import cn.cloudartisan.crius.widget.CustomProgressDialog;

import java.util.HashMap;

public abstract class CIMMonitorFragment extends Fragment implements CIMEventListener {
    public HashMap<String, Object> apiParams;
    private CustomProgressDialog progressDialog;
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        CIMListenerManager.registerMessageListener(this, getActivity());
    }
    
    public void onDestroy() {
        super.onDestroy();
        CIMListenerManager.removeMessageListener(this);
    }
    
    public View findViewById(int id) {
        return getView().findViewById(id);
    }
    
    public void showProgressDialog(String content, boolean cancancelable) {
        progressDialog = new CustomProgressDialog(getActivity());
        progressDialog.setMessage(content);
        progressDialog.setCancelable(cancancelable);
        progressDialog.show();
    }
    
    public void showProgressDialog(String content) {
        showProgressDialog(content, false);
    }
    
    public void hideProgressDialog() {
        if((progressDialog != null) && (progressDialog.isShowing())) {
            progressDialog.dismiss();
        }
    }
    
    public void onConnectionStatus(boolean isConnected) {
    }
    
    public void onReplyReceived(ReplyBody reply) {
    }
    
    public void onMessageReceived(Message arg0) {
        Log.e("frag","base");
    }
    
    public void onNetworkChanged(NetworkInfo info) {
    }
}
