/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.contact;

import android.content.Intent;
import android.view.Menu;
import android.view.View;
import android.widget.Button;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.component.GroupListPanel;
import cn.cloudartisan.crius.ui.base.BaseActivity;

public class GroupListActivity extends BaseActivity {
    protected GroupListPanel groupListPanel;
    
    public void initComponents() {
        setDisplayHomeAsUpEnabled(true);
        groupListPanel = (GroupListPanel)findViewById(R.id.groupList);
        findViewById(R.id.bar_my_created).setOnClickListener(this);
        findViewById(R.id.bar_my_created).setSelected(true);
        findViewById(R.id.bar_my_join).setOnClickListener(this);
    }
    
    public void onResume() {
        super.onResume();
        groupListPanel.loadGroups(findViewById(R.id.bar_my_created).isSelected() ? 0x0 : 0x1);
    }
    
    public int getConentLayout() {
        return R.layout.activity_grouplist;
    }
    
    public int getActionBarTitle() {
        return R.string.common_mygroups;
    }
    
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.single_button, menu);
        Button button =(Button)menu.findItem(R.id.menu_button).getActionView().findViewById(R.id.button);
        button.setOnClickListener(this);
        button.setText(R.string.common_create);
        return super.onCreateOptionsMenu(menu);
    }
    
    public void onClick(View v) {
        if(R.id.button == v.getId()) {
            startActivity(new Intent(this, CreateGroupActivity.class));
        }
        if(R.id.bar_my_created == v.getId()) {
            findViewById(R.id.bar_my_join).setSelected(false);
            findViewById(R.id.bar_my_created).setSelected(true);
            groupListPanel.toogleMyCreatedGroup();
        }
        if(R.id.bar_my_join == v.getId()) {
            findViewById(R.id.bar_my_created).setSelected(false);
            findViewById(R.id.bar_my_join).setSelected(true);
            groupListPanel.toogleMyJoinGroup();
        }
    }
}
