/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.widget;

import android.app.Dialog;
import android.content.Context;
import android.widget.TextView;
import cn.cloudartisan.crius.R;

public class CustomProgressDialog extends Dialog {
    
    public CustomProgressDialog(Context context) {
        super(context, R.style.custom_dialog);
        setContentView(R.layout.progress_dialog);
        setCancelable(true);
    }
    
    public void setMessage(CharSequence message) {
        ((TextView)findViewById(R.id.progress_dialog_msg)).setText(message);
    }
}
