/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.widget;

import android.view.View;
import android.app.Dialog;
import android.content.Context;
import android.widget.TextView;
import android.os.Vibrator;
import android.view.animation.AnimationUtils;
import cn.cloudartisan.crius.R;

public class OptionsDialog extends Dialog implements View.OnClickListener {
    Context context;
    private View mDialogView;
    OptionsDialog.OnOperationListener operationListener;
    
    public OptionsDialog(Context context) {
        super(context, R.style.custom_dialog);
        setContentView(R.layout.custom_options_dialog);
        //mDialogView = getWindow().getDecorView().findViewById(0x1020002);
        mDialogView=getWindow().getDecorView().findViewById(R.id.opt_dialog);
        findViewById(R.id.copy).setOnClickListener(this);
        findViewById(R.id.delete).setOnClickListener(this);
        this.context = context;
        setCanceledOnTouchOutside(true);
    }
    
    public void setOperationListener(OptionsDialog.OnOperationListener operationListener) {
        this.operationListener = operationListener;
    }
    
    public void hide(int id) {
        findViewById(id).setVisibility(View.GONE);
    }
    
    public void setTitle(CharSequence title) {
        ( (TextView)findViewById(R.id.title)).setText(title);
    }
    
    public void setTag(Object tag) {
        findViewById(R.id.title).setTag(tag);
    }
    
    public Object getTag() {
        return findViewById(R.id.title).getTag();
    }
    
    public void show() {
        ((Vibrator)context.getSystemService(Context.VIBRATOR_SERVICE)).vibrate(0xf);
        mDialogView.startAnimation(AnimationUtils.loadAnimation(getContext(), R.anim.dialog_in));
        super.show();
    }
    
    public void onClick(View v) {
        operationListener.onItemClick(v);
    }
    public  interface OnOperationListener
    {
        void onItemClick(View paramView);
    }
}
