/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.widget;

import android.content.Context;
import android.graphics.drawable.ColorDrawable;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.PopupWindow;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.component.WebImageView;
import cn.cloudartisan.crius.util.FileURLBuilder;

public class SettingMenuWindow extends PopupWindow implements View.OnClickListener {
    View.OnClickListener clickListener;
    
    public SettingMenuWindow(Context context, View.OnClickListener listener) {
        super(context, null);
        clickListener = listener;
        View view = LayoutInflater.from(context).inflate(R.layout.layout_setting_dropdow_menu, null);
        view.findViewById(R.id.menu_profile).setOnClickListener(this);
        view.findViewById(R.id.menu_seeting).setOnClickListener(this);
        view.findViewById(R.id.menu_album).setOnClickListener(this);
        User user = Global.getCurrentUser();
        WebImageView icon = (WebImageView)view.findViewById(R.id.icon);
        icon.load(FileURLBuilder.getUserIconUrl(user.getAccount()));
        TextView name = (TextView)view.findViewById(R.id.username);
        TextView account = (TextView)view.findViewById(R.id.account);
        name.setText(user.getName());
        account.setText(user.getAccount());
        setContentView(view);
        setWidth(-0x2);
        setHeight(-0x2);
        setOutsideTouchable(true);
        setBackgroundDrawable(new ColorDrawable(0x0));
        setFocusable(true);
    }
    
    public void onClick(View v) {
        clickListener.onClick(v);
    }
}
