/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.widget;

import android.app.Dialog;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.component.ProgressbarPhotoView;
import android.content.Context;
import android.view.View;
import cn.cloudartisan.crius.bean.OSSImage;

public class SinglePhotoViewDialog extends Dialog implements ProgressbarPhotoView.OnPhotoViewClickListener {
    Context mContext;
    ProgressbarPhotoView photoView;
    
    public SinglePhotoViewDialog(Context context) {
        super(context, R.style.theme_dialog_fullscreen);
        setContentView(R.layout.dialog_single_photoview);
        photoView = (ProgressbarPhotoView)findViewById(R.id.progressbarPhotoView);
        mContext = context;
        photoView.setOnPhotoViewClickListener(this);
    }
    
    public void show(OSSImage image) {
        super.show();
        photoView.display(image);
    }
    
    public void show(String imageUrl) {
        super.show();
        photoView.display(imageUrl);
    }
    
    public void onPhotoViewClicked(View view) {
        dismiss();
    }
}
