/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.widget;

import android.text.style.ClickableSpan;
import android.content.Context;
import android.view.View;
import android.content.Intent;
import cn.cloudartisan.crius.ui.chat.MMWebViewActivity;

public class URLClickableSpan extends ClickableSpan {
    Context context;
    private String mUrl;
    
    public URLClickableSpan(String url, Context context) {
        context = context;
        mUrl = url;
    }
    
    public void onClick(View widget) {
        Intent intent = new Intent(context, MMWebViewActivity.class);
        intent.putExtra("url", mUrl);
        context.startActivity(intent);
    }
}
