/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.parser;

import cn.cloudartisan.crius.bean.Message;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.adapter.SystemMsgListViewAdapter;
import java.util.HashMap;
import cn.cloudartisan.crius.bean.MessageItemSource;
import cn.cloudartisan.crius.bean.SystemMsg;

public abstract class MessageParser {
    
    public abstract void displayInSysMsgListView(SystemMsgListViewAdapter.MessageViewHolder p1, Message p2);
    
    
    public abstract void encodeContent(HashMap<String,Object> p1);
    
    
    public abstract String getMessagePreview(Message p1);
    
    
    public Object decodeContent(Message message) {
        return JSON.parseObject(message.content);
    }
    
    public MessageItemSource getMessageItemSource(Message message) {
        return new SystemMsg(message.type);
    }
}
