/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.parser;

import android.view.View;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.SystemMsgListViewAdapter;
import cn.cloudartisan.crius.bean.Message;

import java.util.HashMap;

public class SystemMessageParser extends MessageParser {
    
    public HashMap<String, Object> decodeContent(Message msg) {
        return null;
    }
    
    public void displayInSysMsgListView(SystemMsgListViewAdapter.MessageViewHolder holder, Message message) {
        holder.content.setText(message.content.trim());
        holder.content.setVisibility(View.VISIBLE);
        holder.name.setVisibility(View.GONE);
        holder.headImageView.setImageResource(R.drawable.icon_system_message);
    }
    
    public void encodeContent(HashMap data) {
    }
    
    public String getMessagePreview(Message message) {
        return message.content;
    }
}
