/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.parser;

import cn.cloudartisan.crius.adapter.SystemMsgListViewAdapter;
import cn.cloudartisan.crius.bean.Message;
import java.util.HashMap;
import cn.cloudartisan.crius.bean.MessageItemSource;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.bean.Bottle;

public class Type700MessageParser extends MessageParser {
    
    public void displayInSysMsgListView(SystemMsgListViewAdapter.MessageViewHolder holder, Message message) {
    }
    
    public void encodeContent(HashMap<String, Object> data) {
    }
    
    public String getMessagePreview(Message message) {
        return "\u4f60\u6536\u5230\u4e86\u4e00\u6761\u6f02\u6d41\u74f6\u6d88\u606f";
    }
    
    public MessageItemSource getMessageItemSource(Message message) {
        return (MessageItemSource)JSON.parseObject(JSON.parseObject(message.content).getString("bottle"), Bottle.class);
    }
}
