/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.parser;

import android.view.View;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.SystemMsgListViewAdapter;
import cn.cloudartisan.crius.app.LvxinApplication;
import cn.cloudartisan.crius.bean.Friend;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.util.FileURLBuilder;

import java.util.HashMap;

public class Type101MessageParser extends MessageParser {
    
    public String getMessagePreview(Message msg) {
        StringBuffer sb = new StringBuffer();
        sb.append(LvxinApplication.getInstance().getString(R.string.tip_agree_addfriend, new Object[] {JSON.parseObject(msg.content).getString("targetName")}));
        return sb.toString();
    }
    
    public void displayInSysMsgListView(SystemMsgListViewAdapter.MessageViewHolder holder, Message message) {
        Friend friend = (Friend)decodeContent(message);
        holder.name.setVisibility(View.GONE);
        holder.headImageView.load(FileURLBuilder.getUserIconUrl(friend.account), R.drawable.icon_head_default);
        holder.content.setText(getMessagePreview(message));
    }
    
    public Object decodeContent(Message message) {
        Friend targetUser = new Friend();
        JSONObject json = JSON.parseObject(message.content);
        targetUser.account = json.getString("targetAccount");
        targetUser.name = json.getString("targetName");
        return targetUser;
    }
    
    public void encodeContent(HashMap inputData) {
        HashMap<String, String> contentData = new HashMap<String, String>();
        contentData.put("targetAccount", ((User)inputData.get("user")).getAccount());
        contentData.put("targetName", ((User)inputData.get("user")).getName());
        ( (Message)inputData.get("message")).content = JSON.toJSONString(contentData);
    }
}
