/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.parser;

import cn.cloudartisan.crius.bean.Message;
import java.util.HashMap;
import cn.cloudartisan.crius.adapter.SystemMsgListViewAdapter;
import cn.cloudartisan.crius.bean.MessageItemSource;
import cn.cloudartisan.crius.db.PublicAccountDBManager;
import cn.cloudartisan.crius.bean.PubLinkMessage;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.bean.PubLinksMessage;
import cn.cloudartisan.crius.bean.PubTextMessage;

public class Type201MessageParser extends MessageParser {
    
    public MessageItemSource getMessageItemSource(Message msg) {
        return PublicAccountDBManager.getManager().queryPublicAccount(msg.sender);
    }
    
    public HashMap<String, Object> decodeContent(Message msg) {
        return null;
    }
    
    public void displayInSysMsgListView(SystemMsgListViewAdapter.MessageViewHolder holder, Message message) {
    }
    
    public void encodeContent(HashMap<String, Object> data) {
    }
    
    public String getMessagePreview(Message message) {
        if("5".equals(message.fileType)) {
            PubLinkMessage link = (PubLinkMessage)JSON.parseObject(message.content, PubLinkMessage.class);
            return link.title;
        }
        if("6".equals(message.fileType)) {
            PubLinksMessage link = (PubLinksMessage)JSON.parseObject(message.content, PubLinksMessage.class);
            return link.title;
        }
        if("0".equals(message.fileType)) {
            PubTextMessage text = (PubTextMessage)JSON.parseObject(message.content, PubTextMessage.class);
            return text.content;
        }
        return message.content;
    }
}
