/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.parser;

import android.view.View;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.SystemMsgListViewAdapter;
import cn.cloudartisan.crius.app.CriusApplication;
import cn.cloudartisan.crius.bean.Message;

public class Type105MessageParser extends Type102MessageParser {
    
    public String getMessagePreview(Message msg) {
        JSONObject json = JSON.parseObject(msg.content);
        StringBuffer sb = new StringBuffer();
        sb.append(CriusApplication.getInstance().getString(R.string.tip_request_invitegroup,

                        json.getString("sourceName"),
                        json.getString("targetGroupName")
                )
        );
        return sb.toString();
    }
    
    public void displayInSysMsgListView(SystemMsgListViewAdapter.MessageViewHolder holder, Message message) {
        super.displayInSysMsgListView(holder, message);
        holder.name.setVisibility(View.GONE);
        holder.content.setVisibility(View.VISIBLE);
        holder.content.setText(getMessagePreview(message));
    }
}
