/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.chat;

import android.content.Intent;
import android.net.Uri;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.TextView;
import com.alibaba.fastjson.JSON;
import com.baidu.mapapi.map.*;
import com.baidu.mapapi.model.LatLng;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.ui.base.BaseActivity;

public class MapViewActivity extends BaseActivity implements BaiduMap.OnMapLoadedCallback {
    String address;
    double latitude;
    double longitude;
    BaiduMap mBaiduMap;
    private MapView mapView;
    
    public void initComponents() {
        setDisplayHomeAsUpEnabled(true);
        mapView = (MapView)findViewById(R.id.mapView);
        mBaiduMap = mapView.getMap();
        mBaiduMap.setOnMapLoadedCallback(this);
        String data = getIntent().getStringExtra("data");
        ( (TextView)findViewById(R.id.text)).setVisibility(View.VISIBLE);
        address = JSON.parseObject(data).getString("address");
        ((TextView)findViewById(R.id.text)).setText(address);
        latitude = JSON.parseObject(data).getDoubleValue("latitude");
        longitude = JSON.parseObject(data).getDoubleValue("longitude");
        LatLng llA = new LatLng(latitude, longitude);
        MarkerOptions options = (new MarkerOptions())
                .position(llA)
                .icon(BitmapDescriptorFactory.fromResource(R.drawable.icon_location));
        OverlayOptions ooA = new MarkerOptions().position(llA).zIndex(0x9).draggable(true);
        mBaiduMap.addOverlay(ooA);
        MapStatusUpdate u = MapStatusUpdateFactory.newLatLng(llA);
        mBaiduMap.animateMapStatus(u);
    }
    
    protected void onResume() {
        super.onResume();
        mapView.onResume();
    }
    
    protected void onPause() {
        super.onPause();
        mapView.onPause();
    }
    
    public void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }
    
    public void onClick(View v) {
    }
    
    public int getConentLayout() {
        return R.layout.activity_map_view;
    }
    
    public int getActionBarTitle() {
        return R.string.common_map;
    }
    
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.single_icon, menu);
        menu.findItem(R.id.menu_icon).setIcon(R.drawable.ic_action_map);
        return super.onCreateOptionsMenu(menu);
    }
    
    public boolean onOptionsItemSelected(MenuItem item) {
        switch(item.getItemId()) {
            case R.id.menu_icon:
            {
                Uri mUri = Uri.parse(latitude + "," + longitude + "?q=" + address);
                Intent mIntent = new Intent("android.intent.action.VIEW", mUri);
                startActivity(mIntent);
                break;
            }
        }
        return super.onOptionsItemSelected(item);
    }
    
    public void onMapLoaded() {
        mBaiduMap.setMapStatus(MapStatusUpdateFactory.zoomTo(13.0f));
    }
}
