/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.trend;

import android.content.Intent;
import android.view.View;
import android.widget.AdapterView;
import com.alibaba.fastjson.TypeReference;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.NearbyListViewAdapter;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Friend;
import cn.cloudartisan.crius.bean.Page;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.component.NearbyPullRefreshListView;
import cn.cloudartisan.crius.network.HttpAPIRequester;
import cn.cloudartisan.crius.network.HttpAPIResponser;
import cn.cloudartisan.crius.ui.base.BaseActivity;
import cn.cloudartisan.crius.ui.contact.UserDetailActivity;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class NearbyUserListActivity extends BaseActivity implements View.OnClickListener, AdapterView.OnItemClickListener, NearbyPullRefreshListView.OnRefreshListener, HttpAPIResponser {
    protected NearbyListViewAdapter adapter;
    private ArrayList<Friend> list=new ArrayList<>();
    HttpAPIRequester requester;
    User self;
    NearbyPullRefreshListView userListView;
    
    public void initComponents() {
        setDisplayHomeAsUpEnabled(true);
        userListView = (NearbyPullRefreshListView)findViewById(R.id.userListView);
        userListView.setOnRefreshListener(this);
        adapter = new NearbyListViewAdapter(this, list);
        userListView.setAdapter(adapter);
        userListView.setOnItemClickListener(this);
        self = Global.getCurrentUser();
        requester = new HttpAPIRequester(this);
        userListView.doRefresh();
    }
    
    public void onClick(View v) {
        v.getId();
    }
    
    public void onItemClick(AdapterView<?> arg0, View arg1, int index, long arg3) {
        Friend member = (Friend)list.get((index - 0x1));
        Intent intent = new Intent(this, UserDetailActivity.class);
        intent.putExtra("user", member);
        startActivity(intent);
    }
    
    public void onRefresh() {
        requester.execute(null, new TypeReference<NearbyUserListActivity>() {}.getType(), URLConstant.USER_NEARBY_URL);
    }
    
    public void onShowNextPage() {
    }
    
    public void onSuccess(Object data, List datalist, Page page, String code, String url) {
        if((datalist != null) && (!datalist.isEmpty())) {
            findViewById(R.id.nonearbyuserimage).setVisibility(View.GONE);
        } else {
            findViewById(R.id.nonearbyuserimage).setVisibility(View.VISIBLE);
        }
        list.clear();
        list.addAll(datalist);
        adapter.notifyDataSetChanged();
        userListView.refreshComplete();
    }
    
    public void onFailed(Exception e) {
        userListView.refreshComplete();
    }
    
    public Map getRequestParams(String code) {
        apiParams.put("account", self.getAccount());
        return apiParams;
    }
    
    public void onRequest() {
    }
    
    public int getConentLayout() {
        return R.layout.activity_trend_nearby;
    }
    
    public int getActionBarTitle() {
        return R.string.label_function_nearby;
    }
}
