/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.trend;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.Toast;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.TypeReference;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.BottleListAdapter;
import cn.cloudartisan.crius.adapter.ProductListAdapter;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Bottle;
import cn.cloudartisan.crius.bean.ChatItem;
import cn.cloudartisan.crius.bean.LiveInfo;
import cn.cloudartisan.crius.bean.NewsInfo;
import cn.cloudartisan.crius.bean.Page;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.client.model.Message;
import cn.cloudartisan.crius.db.BottleDBManager;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.db.ProductDBManager;
import cn.cloudartisan.crius.network.HttpAPIRequester;
import cn.cloudartisan.crius.network.HttpAPIResponser;
import cn.cloudartisan.crius.ui.base.CIMMonitorActivity;
import cn.cloudartisan.crius.widget.CustomDialog;

public class ProductListActivity extends CIMMonitorActivity implements AdapterView.OnItemClickListener,
        CustomDialog.OnOperationListener, AdapterView.OnItemLongClickListener,HttpAPIResponser {
    protected ProductListAdapter adapter;
    CustomDialog customDialog;
    private List<NewsInfo> dataList = new ArrayList();
    HashMap<String, Object> deleteParams = new HashMap();
    ListView messageListView;
    User self;
    HttpAPIRequester requester;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requester = new HttpAPIRequester(this);
        requester.execute(new TypeReference<ProductListActivity>() {
                }.getType(), null,
                URLConstant.getUrl("product", "list"), "GET");
    }

    public void initComponents() {
        setDisplayHomeAsUpEnabled(true);
        self = Global.getCurrentUser();
        messageListView = (ListView) findViewById(R.id.messageListView);
        messageListView.setOnItemClickListener(this);
        messageListView.setOnItemLongClickListener(this);
        customDialog = new CustomDialog(this);
        customDialog.setOperationListener(this);
        customDialog.setTitle(R.string.common_delete);
        customDialog.setMessage(getString(R.string.tip_clear_bottle));
        customDialog.setButtonsText(getString(R.string.common_cancel), getString(R.string.common_confirm));
    }

    public void onResume() {
        super.onResume();
        dataList.clear();
        dataList.addAll(ProductDBManager.getManager().queryProductList());
        adapter = new ProductListAdapter(this, dataList);
        messageListView.setAdapter(adapter);
    }

    public void onMessageReceived(Message msg) {
       /* if(("700".equals(msg.getType())) || ("701".equals(msg.getType()))) {
            dataList.clear();
            dataList.addAll(BottleDBManager.getManager().queryBottleList());
            adapter.notifyDataSetChanged();
        }*/
    }

    public void onClick(View view) {
    }

    public int getConentLayout() {
        return R.layout.activity_circle_message;
    }

    public int getActionBarTitle() {
        return R.string.label_respository_product_manager;
    }

    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Intent intent = new Intent(this, ArticleDetailedActivity.class);
        intent.putExtra(NewsInfo.class.getSimpleName(), (Serializable) dataList.get(position));
        startActivity(intent);
    }

    public void onLeftClick() {
        customDialog.dismiss();
    }

    public void onRightClick() {
        customDialog.dismiss();
        NewsInfo target = (NewsInfo) customDialog.getTag();
        ProductDBManager.getManager().deleteById(String.valueOf(target.getId()));


        //HttpAPIRequester.execute(deleteParams,  URLConstant.BOTTLE_DELETE_URL);
        //apiParams.put("content", target.gid);
        //apiParams.put("type", "701");
        //HttpAPIRequester.execute(apiParams, URLConstant. MESSAGE_SEND_URL);
        dataList.remove(target);
        adapter.notifyDataSetChanged();
        Intent intent = new Intent("com.farsunset.cim.DELETE_APPEND");
        intent.putExtra(ChatItem.NAME, new ChatItem((Bottle) customDialog.getTag()));
        sendBroadcast(intent);
    }

    public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
        customDialog.setTag(dataList.get(position));
        customDialog.show();
        return true;
    }

    @Override
    public Map getRequestParams(String code) {
        HashMap mp = new HashMap();
        mp.put("channel_id", "2");
        mp.put("category_id", "52");
        return null;
    }

    @Override
    public void onFailed(Exception p1) {

    }

    @Override
    public void onRequest() {

    }

    @Override
    public void onSuccess(Object data, List list, Page page, String code, String url) {
        JSONObject json = (JSONObject) data;
        hideProgressDialog();
        if (json.getBoolean("success")) {

            loadNews(json);


        } else {
            String str = json.getString("message");
            Toast.makeText(this, str, Toast.LENGTH_LONG);
        }
    }

    public void loadNews(JSONObject json) {
        JSONArray list = json.getJSONArray("data");
        dataList.clear();
        // this.newList.clear();
        for (Object obj : list
                ) {
            NewsInfo info = new NewsInfo();
            JSONObject object = (JSONObject) obj;
            info.setBrief((String) object.get("brief"));
            info.setLink((String) object.get("link"));
            info.setComments(object.getInteger("comments"));
            info.setImgThumbs(object.getString("img_thumbs"));
            info.setId(( object.getInteger("id")));
            info.setPublishTime(((JSONObject) obj).getString("publish_time"));

            //info.setComments((Integer) object.get("Team2"));
            //info.setImgThumbs((String)object.get("imgThumbs"));
            //info.setTime((String) object.get("Time"));
            dataList.add(info);
        }


        adapter.notifyDataSetChanged();
        //newsListView.showMoreComplete((Boolean)json.get("hasMore"));
        // newsListView.showMoreComplete(true);
    }
}