/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.ui.trend;

import android.content.Intent;
import android.view.View;
import android.widget.AdapterView;
import com.alibaba.fastjson.TypeReference;
import cn.cloudartisan.crius.client.constant.CIMConstant;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.MyCircleListViewAdapter;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Article;
import cn.cloudartisan.crius.bean.Friend;
import cn.cloudartisan.crius.bean.Page;
import cn.cloudartisan.crius.component.MyCircleLoadMoreListView;
import cn.cloudartisan.crius.component.WebImageView;
import cn.cloudartisan.crius.db.ArticleDBManager;
import cn.cloudartisan.crius.network.HttpAPIRequester;
import cn.cloudartisan.crius.network.HttpAPIResponser;
import cn.cloudartisan.crius.ui.base.BaseActivity;
import cn.cloudartisan.crius.ui.contact.UserDetailActivity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

public class UCircleHomeActivity extends BaseActivity implements MyCircleLoadMoreListView.OnRefreshListener, HttpAPIResponser, AdapterView.OnItemClickListener {
    protected MyCircleListViewAdapter adapter;
    MyCircleLoadMoreListView circleListView;
    int currentPage;
    Friend friend;
    private List<Article> list=new ArrayList<>();
    HttpAPIRequester requester;
    
    public void initComponents() {
        setDisplayHomeAsUpEnabled(true);
        friend = (Friend)getIntent().getSerializableExtra("friend");
        setTitle(friend.getTitle());
        circleListView = (MyCircleLoadMoreListView)findViewById(R.id.circleListView);
        circleListView.setOnRefreshListener(this);
        ( (WebImageView)circleListView.findViewById(R.id.icon)).displayAtBackground(friend.getWebIcon(), R.drawable.icon_head_default);
        circleListView.setOnItemClickListener(this);
        circleListView.findViewById(R.id.icon).setOnClickListener(this);
        list.addAll(ArticleDBManager.getManager().queryArticles(friend.account, currentPage));
        adapter = new MyCircleListViewAdapter(this, list);
        circleListView.setAdapter(adapter);
        requester = new HttpAPIRequester(this);
        requester.execute(null, new TypeReference<UCircleHomeActivity>() {
            }.getType(), URLConstant.ARTICLE_MYLIST_URL);
        Article article =new Article();
        article.account="15216700472";
        article.comment="";
        article.content="{content:'ccccc'}";
        article.type="0";
        article.gid="24344545";
        article.timestamp=String.valueOf(new Date().getTime());
        list.add(article);
    }
    
    public void onClick(View v) {
        if(v.getId() == R.id.icon) {
            Intent intent = new Intent(this, UserDetailActivity.class);
            intent.putExtra("user", friend);
            startActivity(intent);
        }
    }
    
    public void onShowNextPage() {
        currentPage = (currentPage + 0x1);
        requester.execute(null, new TypeReference<UCircleHomeActivity>() {
         }.getType(), URLConstant.ARTICLE_MYLIST_URL);
    }
    
    public void onSuccess(Object data, List datalist, Page page, String code, String url) {
        MyCircleLoadMoreListView var7 = this.circleListView;
        boolean var6;
        if(datalist != null && !datalist.isEmpty() && datalist.size() % 10 == 0) {
            var6 = true;
        } else {
            var6 = false;
        }

        var7.showMoreComplete(var6);
        this.setProgressBarIndeterminateVisibility(false);
        if(CIMConstant.ReturnCode.CODE_200.equals(url)) {
            if(datalist != null && !datalist.isEmpty()) {
                if(this.currentPage == 1) {
                    this.list.clear();
                }

                ArticleDBManager.getManager().save(datalist);
                this.list.addAll(datalist);
                this.adapter.notifyDataSetChanged();
            } else if(this.currentPage > 1) {
                --this.currentPage;
                return;
            }
        }
    }
    
    public void onFailed(Exception e) {
        circleListView.showMoreComplete(true);
    }
    
    public Map getRequestParams(String code) {
        apiParams.put("account", friend.account);
        apiParams.put("currentPage", Integer.valueOf(currentPage));
        return apiParams;
    }
    
    public void onRequest() {
        setProgressBarIndeterminateVisibility(true);
    }
    
    public int getConentLayout() {
        return R.layout.activity_trend_my_circle;
    }
    
    public int getActionBarTitle() {
        return 0x0;
    }
    
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Intent intent = new Intent(this, ArticleDetailedActivity.class);
        intent.putExtra("article", (Serializable)list.get((position - 0x1)));
        startActivity(intent);
    }
}
