/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.graphics.Bitmap;
import android.util.AttributeSet;
import android.view.View;
import android.widget.GridView;
import android.widget.ImageView;
import com.nostra13.universalimageloader.core.ImageLoader;
import com.nostra13.universalimageloader.core.listener.SimpleImageLoadingListener;

public class BannerFunView extends ImageView {

    private final String NAMESPACE = "http://schemas.android.com/apk/res/android";
    int mWidth;
    int resouceId;
GridView gridView;
    public BannerFunView(Context paramContext, AttributeSet paramAttributeSet)
    {
        super(paramContext, paramAttributeSet, 0);
        this.resouceId = paramAttributeSet.getAttributeResourceValue("http://schemas.android.com/apk/res/android", "tag", 0);
        this.mWidth = getResources().getDisplayMetrics().widthPixels;
        ImageLoader.getInstance().displayImage("drawable://" + this.resouceId, this, new SimpleImageLoadingListener()
        {
            public void onLoadingComplete(String paramAnonymousString, View paramAnonymousView, Bitmap paramAnonymousBitmap)
            {
                int i = paramAnonymousBitmap.getWidth();
                int j = paramAnonymousBitmap.getHeight();
                paramAnonymousView.getLayoutParams().height = (BannerFunView.this.mWidth * j / i);
            }
        });
    }


}
