/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.widget.GridView;
import android.content.Context;
import android.util.AttributeSet;

public class CustomGridView extends GridView {
    boolean flag = false;
    
    public CustomGridView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    
    public CustomGridView(Context context) {
        super(context);
    }
    
    public void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        flag = false;
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }
    
    public void onLayout(boolean changed, int l, int t, int r, int b) {
        flag = true;
        super.onLayout(changed, l, t, r, b);
    }
    
    public boolean measured() {
        return flag;
    }
}
