/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.content.Intent;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.adapter.FriendListViewAdapter;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.bean.Friend;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.db.FriendDBManager;
import cn.cloudartisan.crius.ui.chat.FriendChatActivity;
import cn.cloudartisan.crius.util.AppTools;

import java.util.ArrayList;

public class FriendListPanel extends ListView implements AdapterView.OnItemClickListener {
    public FriendListViewAdapter adapter;
    Context context;
    TextView footer;
    User self;
    private ArrayList<Friend> list = new ArrayList();
    
    public FriendListPanel(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        init(paramContext);
    }
    
    public void init(Context paramContext) {
        context = paramContext;
        View header = LayoutInflater.from(paramContext).inflate(R.layout.layout_contacts_header, null);
        footer = (TextView)LayoutInflater.from(paramContext).inflate(R.layout.layout_contacts_footer, null);
        addFooterView(footer, 0x0, false);
        AppTools.measureView(header);
        addHeaderView(header, 0x0, false);
        adapter = new FriendListViewAdapter(context, list);
        setAdapter(adapter);
        setOnItemClickListener(this);
    }
    
    public void addUser(Friend f) {
        list.add(f);
        adapter.notifyDataSetChanged();
    }
    
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Intent intent = new Intent(context, FriendChatActivity.class);
        Friend friend=list.get(position-1);
        intent.putExtra("othersId", friend.account);
        intent.putExtra("othersName", friend.name);
        context.startActivity(intent);
    }
    
    public void loadFriends(FriendListPanel.LoadFriendListener listener) {
        self = Global.getCurrentUser();
        list.clear();
        Friend friend=new Friend();
        friend.account="15216700472";
        friend.fristChar="w";
        friend.gender="0";
        friend.name="吴友琴";
        friend.online="1";
        friend.motto="1";
        list.add(0,friend);
        list.addAll(FriendDBManager.getManager().queryFriendList());
        adapter.notifyDataSetChanged();
        listener.completed(list.size());
        footer.setText(context.getString(R.string.label_contacts_frend_count, new Object[] {Integer.valueOf(list.size())}));
    }
    
    public int getFriendCount() {
        return list.size();
    }
    public  interface LoadFriendListener
    {
        void completed(int paramInt);
    }
}
