/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.util.AttributeSet;

public class FromMessageFileView extends FromMessageView {
    
    public FromMessageFileView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void displayMessage() {
        others_file_layout.initView(message);
        message_content.setOnClickListener(others_file_layout);
    }
}
