/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.support.v4.view.ViewPager;
import android.content.Context;
import android.util.AttributeSet;
import android.view.MotionEvent;

public class GalleryViewPager extends ViewPager {
    
    public GalleryViewPager(Context context) {
        super(context);
    }
    
    public GalleryViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch(IllegalArgumentException localIllegalArgumentException1) {
        }
        return false;
    }
}
