/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.content.Intent;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.PubLinksMessage;
import cn.cloudartisan.crius.ui.chat.MMWebViewActivity;

public class PubFromMessageLinkPanelView extends PubFromMessageView implements View.OnClickListener {
    LinearLayout linkPanelView;
    
    public PubFromMessageLinkPanelView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void onFinishInflate() {
        super.onFinishInflate();
        linkPanelView = (LinearLayout)findViewById(R.id.linksPanelView);
    }
    
    public void displayMessage() {
        linkPanelView.setOnLongClickListener(this);
        PubLinksMessage linkMsg =JSON.parseObject(message.content, PubLinksMessage.class);
        linkPanelView.removeAllViews();
        View topLine = LayoutInflater.from(_context).inflate(R.layout.layout_pubchat_linkbanner, null);
        ((TextView)topLine.findViewById(R.id.title)).setText(linkMsg.title);
        WebImageView image = (WebImageView)topLine.findViewById(R.id.banner);
        image.setImageResource(R.color.window_bg);
        image.load(linkMsg.image);
        topLine.setTag(linkMsg.link);
        topLine.setOnClickListener(this);
        linkPanelView.addView(topLine);
        if(linkMsg.hasMore()) {
            topLine.setBackgroundResource(R.drawable.item_background_top);

            for(int i=0;i<linkMsg.items.size();i++){
                View item = LayoutInflater.from(_context).inflate(R.layout.layout_pubchat_itemlink, null);
                ((TextView)item.findViewById(R.id.title)).setText(linkMsg.getSubLink(i).title);
                WebImageView iconImage = (WebImageView)item.findViewById(R.id.image);
                iconImage.setImageResource(R.color.window_bg);
                iconImage.load(linkMsg.getSubLink(i).image);
                linkPanelView.addView(item);
                item.setTag(linkMsg.getSubLink(i).link);
                item.setOnClickListener(this);
                if(i == linkMsg.items.size()) {
                    item.setBackgroundResource(R.drawable.item_background_bottom);
                }else{
                    item.setBackgroundResource(R.drawable.item_background_middle);
                }

            }

        }
        topLine.setBackgroundResource(R.drawable.item_background_single);
    }
    
    public Object getTag() {
        return linkPanelView.getTag(R.id.logo);
    }
    
    public void setTag(Object obj) {
        linkPanelView.setTag(R.id.logo, obj);
    }
    
    public void onClick(View v) {
        Intent intent = new Intent(_context, MMWebViewActivity.class);
        intent.putExtra("url", v.getTag().toString());
        _context.startActivity(intent);
    }
}
