/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.content.Intent;
import android.util.AttributeSet;
import android.view.View;
import android.widget.TextView;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.PubLinkMessage;
import cn.cloudartisan.crius.ui.chat.MMWebViewActivity;

public class PubFromMessageLinkView extends PubFromMessageView implements View.OnClickListener {
    WebImageView banner;
    TextView descrpiton;
    PubLinkMessage linkMsg;
    TextView title;
    
    public PubFromMessageLinkView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void onFinishInflate() {
        super.onFinishInflate();
        title = (TextView)findViewById(R.id.title);
        descrpiton = (TextView)findViewById(R.id.descrpiton);
        banner = (WebImageView)findViewById(R.id.banner);
    }
    
    public void displayMessage() {
        findViewById(R.id.linkPanelView).setOnLongClickListener(this);
        linkMsg =JSON.parseObject(message.content, PubLinkMessage.class);
        title.setText(linkMsg.title);
        descrpiton.setText(linkMsg.content);
        banner.setImageResource(R.color.window_bg);
        banner.load(linkMsg.image);
        findViewById(R.id.linkPanelView).setOnClickListener(this);
    }
    
    public Object getTag() {
        return findViewById(R.id.linkPanelView).getTag(R.id.logo);
    }
    
    public void setTag(Object obj) {
        findViewById(R.id.linkPanelView).setTag(R.id.logo, obj);
    }
    
    public void onClick(View v) {
        Intent intent = new Intent(_context, MMWebViewActivity.class);
        intent.putExtra("url", linkMsg.link);
        _context.startActivity(intent);
    }
}
