/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;
import com.alibaba.fastjson.parser.Feature;
import com.nostra13.universalimageloader.core.ImageLoader;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.Article;
import cn.cloudartisan.crius.bean.OSSImage;
import cn.cloudartisan.crius.bean.SNSImage;
import cn.cloudartisan.crius.util.StringUtils;
import cn.cloudartisan.crius.widget.GalleryPhotoViewDialog;
import cn.cloudartisan.crius.widget.SinglePhotoViewDialog;

import java.util.List;

public class SNSImageView extends WebImageView implements View.OnClickListener {
    Context _context;
    private SNSImage image;
    
    public SNSImageView(Context context) {
        super(context);
        setOnClickListener(this);
        _context = context;
    }
    
    public SNSImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
        setOnClickListener(this);
        _context = context;
    }
    
    public void display(Article target, SNSImage image) {
        setTag(target);
       this.image = image;
        setImageResource(R.color.def_imageview_color);
      ImageLoader.getInstance().displayImage(StringUtils.getOSSFileURI("lvxin-files", image.thumbnail), this, options);
    }
    
    public void display(Article target, SNSImage image, int w, int h) {
        this.image = image;
        setTag(target);
        int circleSinglePhotoSide = _context.getResources().getDimensionPixelOffset(R.dimen.circle_single_photo_side);
        if((w < circleSinglePhotoSide) && (h < circleSinglePhotoSide)) {
            getLayoutParams().width = w;
            getLayoutParams().height = h;
        } else if(w >= h) {
            getLayoutParams().width = circleSinglePhotoSide;
            getLayoutParams().height = ((circleSinglePhotoSide * h) / w);
        } else {
            getLayoutParams().height = circleSinglePhotoSide;
            getLayoutParams().width = ((circleSinglePhotoSide * w) / h);
        }
        setImageResource(R.color.def_imageview_color);
       // ImageLoader.getInstance().displayImage(StringUtils.getOSSFileURI("lvxin-files", image.image), this, options);
    }
    
    public void onClick(View view) {
        Article target = (Article)view.getTag();
        List<OSSImage> snsImageList = JSON.parseObject(target.thumbnail, new TypeReference<SNSImageView>() {
        }.getType(), new Feature[0x0]);
        snsImageList.remove(image);
        snsImageList.add(0x0, image);
        if(snsImageList.size() == 0x1) {
            image.thumbnail = image.image;
            SinglePhotoViewDialog dialog = new SinglePhotoViewDialog(_context);
            dialog.show(image);
            return;
        }
        GalleryPhotoViewDialog dialog = new GalleryPhotoViewDialog(_context);
        dialog.show(snsImageList);
    }
}
