/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.util.AttributeSet;

public class ToMessageVoiceView extends ToMessageView {
    
    public ToMessageVoiceView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void displayMessage() {
        my_voice_layout.initView(message.sender.equals(self.getAccount()), message);
        message_content.setOnClickListener(my_voice_layout);
    }
}
