/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.util.AttributeSet;
import com.alibaba.fastjson.JSON;
import android.view.View;

public class ToMessageFileView extends ToMessageView {
    
    public ToMessageFileView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void displayMessage() {
        my_file_layout.setTag(JSON.parseObject(message.content).getString("objectKey"));
        my_file_layout.initView(message);
        message_content.setOnClickListener(my_file_layout);
        sendProgressbar.setVisibility(View.GONE);
        if(message.status.equals("-2")) {
            my_file_layout.progressBar.setVisibility(View.VISIBLE);
        }
    }
}
