/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.bean.MessageItemSource;
import cn.cloudartisan.crius.bean.User;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.network.SendMessageRequester;
import cn.cloudartisan.crius.util.FileURLBuilder;
import cn.cloudartisan.crius.widget.OptionsDialog;

public abstract class ToMessageView extends RelativeLayout implements View.OnLongClickListener, OptionsDialog.OnOperationListener, View.OnClickListener {
    ChatListView.OnMessageDeleteListenter OnMessageDeleteListenter;
    public Context _context;
    View icon_resend;
    Message message;
    View message_content;
    ChatFileView my_file_layout;
    WebImageView my_headImageView;
    ChatWebImageView my_image_layout;
    ChatMapView my_map_layout;
    EmoticonsTextView my_text;
    ChatVoiceView my_voice_layout;
    OptionsDialog optionsDialog;
    MessageItemSource others;
    private TextView readMark;
    SendMessageRequester requester;
    User self;
    ProgressBar sendProgressbar;
    
    protected abstract void displayMessage();
    
    
    public ToMessageView(Context context) {
        super(context);
        _context = context;
    }
    
    public ToMessageView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void setOnMessageDeleteListenter(ChatListView.OnMessageDeleteListenter onMessageDeleteListenter) {
        OnMessageDeleteListenter = onMessageDeleteListenter;
    }
    
    public void onFinishInflate() {
        super.onFinishInflate();
        readMark = (TextView)findViewById(R.id.read_status);
        message_content = findViewById(R.id.message_content);
        message_content.setOnClickListener(null);
        icon_resend = findViewById(R.id.icon_resend);
        icon_resend.setOnClickListener(this);
        sendProgressbar = (ProgressBar)findViewById(R.id.sendinProgressbar);
        my_headImageView = (WebImageView)findViewById(R.id.my_headImageView);
        my_text = (EmoticonsTextView)findViewById(R.id.my_text);
        my_image_layout = (ChatWebImageView)findViewById(R.id.my_image_layout);
        my_voice_layout = (ChatVoiceView)findViewById(R.id.my_voice_layout);
        my_file_layout = (ChatFileView)findViewById(R.id.my_file_layout);
        my_map_layout = (ChatMapView)findViewById(R.id.my_map_layout);
        message_content.setOnLongClickListener(this);
        optionsDialog = new OptionsDialog(_context);
        optionsDialog.setOperationListener(this);
    }
    
    public final void displayMessage(Message message, User self, MessageItemSource others) {
        this.message = message;
        this.self = self;
        this.others = others;
        setTag(message);
        readMark.setVisibility(View.GONE);
        my_headImageView.load(FileURLBuilder.getUserIconUrl(self.getAccount()), R.drawable.icon_head_default);
        message_content.setOnClickListener(null);
        displayMessage();
        statusHandler();
    }
    
    private void statusHandler() {
        if("-2".equals(message.status)) {
            showSendProgressbar();
        } else {
            sendProgressbar.setVisibility(View.GONE);
        }
        if("-3".equals(message.status)) {
            icon_resend.setVisibility(View.VISIBLE);
            icon_resend.setOnClickListener(this);
        } else {
            icon_resend.setVisibility(View.GONE);
        }
        if("-1".equals(message.status)) {
            sendMessage();
        }
        if(("9".equals(message.status)) && (message.isNeedShowReadStatus())) {
            showReadMark();
        }
        if(("1".equals(message.status)) && (message.isNeedShowReadStatus())) {
            showSetMark();
        }
    }
    
    public void showReadMark() {
        message.status = "9";
        readMark.setVisibility(View.VISIBLE);
        readMark.setText(R.string.tip_has_read);
        readMark.setBackgroundResource(R.drawable.bg_status_already_read);
    }
    
    public void showSetMark() {
        readMark.setVisibility(View.VISIBLE);
        readMark.setText(R.string.tip_has_sent);
        readMark.setBackgroundResource(R.drawable.bg_status_already_sent);
    }
    
    private void showSendProgressbar() {
        if(!message.fileType.equals("1")) {
            if(!message.fileType.equals("4")) {
                if(!message.fileType.equals("3")) {
                    sendProgressbar.setVisibility(View.VISIBLE);
                }
            }
        }
    }
    
    private void sendMessage() {
        Message message = (Message)getTag();
        showSendProgressbar();
        icon_resend.setVisibility(View.GONE);
        message.status = "-2";
        MessageDBManager.getManager().updateStatus(message.gid, "-2");
        Intent intent = new Intent();
        intent.putExtra(Message.NAME, message);
        intent.setAction("com.farsunset.cim.SEND_STATUS_CHANGED");
        _context.sendBroadcast(intent);
        requester = new SendMessageRequester(message);
        requester.execute();
    }
    
    public void onMessageSend(Message msg) {
        if("-3".equals(msg.status)) {
            icon_resend.setVisibility(View.VISIBLE);
            sendProgressbar.setVisibility(View.GONE);
        }
        if("1".equals(msg.status)) {
            icon_resend.setVisibility(View.GONE);
            sendProgressbar.setVisibility(View.GONE);
            if(message.isNeedShowReadStatus()) {
                readMark.setVisibility(View.VISIBLE);
                readMark.setText(R.string.tip_has_sent);
                readMark.setBackgroundResource(R.drawable.bg_status_already_sent);
            }
        }
        message.status = msg.status;
    }
    
    public boolean onLongClick(View arg0) {
        Message message = (Message)getTag();
        optionsDialog.show();
        if((message.fileType != null) && (!message.fileType.equals("0"))) {
            optionsDialog.hide(R.id.copy);
        }
        return false;
    }
    
    public void onItemClick(View v) {
        Message message = (Message)getTag();
        optionsDialog.dismiss();
        if(v.getId() == R.id.copy) {
            ClipboardManager cmb = (ClipboardManager)_context.getSystemService(Context.CLIPBOARD_SERVICE);
            cmb.setPrimaryClip(ClipData.newPlainText(null, message.content));
        }
        if(v.getId() == R.id.delete) {
            OnMessageDeleteListenter.onDelete(message);
        }
    }
    
    public void onClick(View v) {
        if(v.getId() == R.id.icon_resend) {
            sendMessage();
        }
    }
}
