/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.util.AttributeSet;
import com.alibaba.fastjson.JSON;
import android.view.View;

public class ToMessageImageView extends ToMessageView {
    
    public ToMessageImageView(Context paramContext, AttributeSet paramAttributeSet) {
        super(paramContext, paramAttributeSet);
        _context = paramContext;
    }
    
    public void displayMessage() {
        String image = JSON.parseObject(message.content).getString("image");
        my_image_layout.setTag(image);
        my_image_layout.initViews(message);
        message_content.setOnClickListener(my_image_layout);
        sendProgressbar.setVisibility(View.GONE);
        if(message.status.equals("-2")) {
            my_image_layout.progressText.setVisibility(View.VISIBLE);
        }
    }
}
