/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.os.Build;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import cn.cloudartisan.crius.util.StringUtils;
import cn.cloudartisan.crius.widget.SinglePhotoViewDialog;
import com.nostra13.universalimageloader.core.DisplayImageOptions;
import com.nostra13.universalimageloader.core.ImageLoader;
import com.nostra13.universalimageloader.core.assist.FailReason;
import com.nostra13.universalimageloader.core.display.RoundedBitmapDisplayer;
import com.nostra13.universalimageloader.core.listener.SimpleImageLoadingListener;

public class WebImageView extends ImageView implements View.OnClickListener {
    Context _context;
    DisplayImageOptions options;
    private String originalUrl;
    
    public WebImageView(Context context) {
        super(context);
        _context = context;
        init();
    }
    
    public WebImageView(Context context, AttributeSet attrs) {
        super(context, attrs, 0x0);
        _context = context;
        init();
    }
    
    public void init() {
        DisplayImageOptions.Builder builder = new DisplayImageOptions.Builder();
        builder.cacheInMemory(true);
        builder.cacheOnDisk(true);
        builder.bitmapConfig(Bitmap.Config.RGB_565);
        if(getRounded() > 0) {
            builder.displayer(new RoundedBitmapDisplayer(getRounded()));
        }
        options = builder.build();
    }
    
    public String getUrl() {
        return originalUrl;
    }
    
    public void setUrl(String url) {
        originalUrl = url;
    }
    
    public void load(String url, int rid) {
        if(rid > 0) {
            setImageResource(rid);
        }
        originalUrl = url;
        ImageLoader.getInstance().displayImage(url, this, options);
    }
    
    public void displayAtBackground(String url,final int rid) {
        if(url.endsWith("null")) {
            return;
        }
        ImageLoader.getInstance().loadImage(url, new SimpleImageLoadingListener() {
            

            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                if(Build.VERSION.SDK_INT > 0xf) {
                    setBackground(new BitmapDrawable(_context.getResources(), loadedImage));
                    return;
                }
                setBackgroundDrawable(new BitmapDrawable(_context.getResources(), loadedImage));
            }
            
            public void onLoadingFailed(String imageUri, View view, FailReason failReason) {
                if(Build.VERSION.SDK_INT > 0xf) {
                    setBackground(_context.getResources().getDrawable(rid));
                    return;
                }
                setBackgroundDrawable(_context.getResources().getDrawable(rid));
            }
        });
    }
    
    public void load(String url) {
        load(url, 0x0);
    }
    
    public void display(String thumb, String originalUrl) {
       this. originalUrl = originalUrl;
        ImageLoader.getInstance().displayImage(thumb, this, options);
    }

    public  void displayResouce(int id){

        this.setBackground(_context.getResources().getDrawable(id));

    }
    
    public void loadLocale(String key) {
        ImageLoader.getInstance().displayImage(StringUtils.getOSSFileURI("lvxin-files", key), this, options);
    }
    
    public int getRounded() {
        return 0x0;
    }
    
    public void setPopuShowAble() {
        setOnClickListener(this);
    }
    
    public void onClick(View view) {
        SinglePhotoViewDialog dialog = new SinglePhotoViewDialog(_context);
        dialog.show(originalUrl);
    }
}
