/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.component;

import android.content.Context;
import android.graphics.Bitmap;
import android.util.AttributeSet;
import android.view.View;
import com.nostra13.universalimageloader.core.DisplayImageOptions;
import com.nostra13.universalimageloader.core.ImageLoader;
import com.nostra13.universalimageloader.core.assist.FailReason;
import com.nostra13.universalimageloader.core.listener.SimpleImageLoadingListener;
import uk.co.senab.photoview.PhotoView;

public class WebPhotoView extends PhotoView {
    Context _context;
    private DisplayImageOptions options;
    
    public WebPhotoView(Context context, AttributeSet attrs) {
        super(context, attrs, 0);
        _context = context;
        DisplayImageOptions.Builder builder = new DisplayImageOptions.Builder();
        builder.cacheInMemory(false);
        builder.cacheOnDisk(true);
        builder.bitmapConfig(Bitmap.Config.RGB_565);
        options = builder.build();
    }
    
    public void display(String imageUrl) {
        ImageLoader.getInstance().displayImage(imageUrl, this, options);
    }
    
    public void loadAliyunOSSFile(String imageUrl,final WebPhotoView.ImageLoadedCallback back) {
        ImageLoader.getInstance().displayImage(imageUrl, this, options, new SimpleImageLoadingListener() {
            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                back.imageLoaded(loadedImage, imageUri);
            }
            
            public void onLoadingFailed(String imageUri, View view, FailReason failReason) {
                back.imageLoaded(null, imageUri);
            }
        });
    }
    public interface ImageLoadedCallback
    {
       void imageLoaded(Bitmap paramBitmap, String paramString);
    }
}
