/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.network;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;
import com.alibaba.fastjson.parser.Feature;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Article;
import cn.cloudartisan.crius.bean.SNSImage;

import java.io.File;
import java.util.HashMap;
import java.util.List;

public class ArticlePublishRequester extends HttpAPIRequester implements FileUploader.OnUploadCallBack {
    public HashMap<String, Object> apiParams = new HashMap();
    
    public ArticlePublishRequester(HttpAPIResponser responser) {
        this.responser = responser;
    }
    
    public void publish(Article article) {
        execute(new TypeReference<ArticlePublishRequester>() {

        }.getType(), null, URLConstant.ARTICLE_PUBLISH_URL);
        if(article.thumbnail == null) {
            return;
        }
        List<SNSImage> snsImageList = (List)JSON.parseObject(article.thumbnail, new TypeReference<ArticlePublishRequester>() {
             }.getType(), new Feature[0x0]);
        for( SNSImage image :snsImageList) {
            FileUploader.asyncUpload(image.image, new File("/" + image.image), this);
            FileUploader.asyncUpload(image.thumbnail, new File("/" + image.thumbnail), this);
        }
    }

    public void complete(String key, File file) {
    }

    public void failed(Exception e, String key) {
        FileUploader.asyncUpload(key, new File("/" + key), this);
    }

    public void onProgress(String key, float progress) {
    }
}
