/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.network;

import com.alibaba.fastjson.TypeReference;
import cn.cloudartisan.crius.client.android.CIMPushManager;
import cn.cloudartisan.crius.client.constant.CIMConstant;
import cn.cloudartisan.crius.app.LvxinApplication;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Page;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HostDispenseRequester extends HttpAPIRequester implements HttpAPIResponser {
    int fileCount;
    public HashMap<String, Object> apiParams = new HashMap();
    int count = 0x0;
    
    public HostDispenseRequester() {
        responser = this;
    }
    
    public void execute() {
        execute(new TypeReference<HostDispenseRequester>() {
        }.getType(), null, URLConstant.HOST_DISPENSE_URL);
    }
    
    public void onSuccess(Object data, List list, Page page, String code, String url) {
        if((CIMConstant.ReturnCode.CODE_200.equals(code)) && (data != null)) {
            CIMPushManager.init(LvxinApplication.getInstance(), data.toString(), 0x70d8);
        }
    }
    
    public void onFailed(Exception e) {
    }
    
    public Map getRequestParams(String code) {
        return apiParams;
    }
    
    public void onRequest() {
    }
}
