/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.network;

import cn.cloudartisan.crius.app.URLConstant;

import java.util.HashMap;

public class MessageReceiptHandler {
    static HashMap<String, Object> apiParams = new HashMap();
    
    public static void handleReceipt(String mid, String type) {
        if(type.startsWith("9")) {
            return;
        }
        apiParams.put("gid", mid);
       HttpAPIRequester.execute(apiParams, URLConstant.MESSAGE_RECEIVED_URL);
    }
}
