/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.network;

import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.text.SpannableStringBuilder;
import android.text.style.ForegroundColorSpan;
import android.text.style.StyleSpan;
import com.alibaba.fastjson.TypeReference;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Config;
import cn.cloudartisan.crius.bean.Page;
import cn.cloudartisan.crius.ui.base.BaseActivity;
import cn.cloudartisan.crius.util.AppTools;
import cn.cloudartisan.crius.widget.CustomDialog;
import cn.cloudartisan.crius.widget.CustomProgressDialog;

import java.io.File;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UpgradeManger implements HttpAPIResponser, CustomDialog.OnOperationListener, FileDownloader.FileDownloadCallBack {
    Context context;
    CustomDialog customDialog;
    FileDownloader downloader;
    File file;
    boolean flag;
    CustomProgressDialog progressDialog;
    HttpAPIRequester requester;
    static UpgradeManger upgradeManger;
    final DecimalFormat format = new DecimalFormat("0.00");
    public Map<String, Object> apiParams = new HashMap();
    
    public UpgradeManger(Context ctx) {
        requester = new HttpAPIRequester(this);
        context = ctx;
        customDialog = new CustomDialog(ctx);
        customDialog.setButtonsText(context.getString(R.string.common_cancel), context.getString(R.string.common_upgrade));
        customDialog.setTitle(context.getString(R.string.tip_find_newversion));
        customDialog.setOperationListener(this);
        downloader = FileDownloader.getInstance();
        downloader.setOnDownloadCallBack(this);
        progressDialog = new CustomProgressDialog(ctx);
    }
    
    public void excute(boolean show) {
        flag = show;
        requester.execute(null, new TypeReference<UpgradeManger>() {
        }.getType(), URLConstant.CONFIG_LIST_URL);
    }
    
    public void onSuccess(Object data, List list, Page page, String code, String url) {
        progressDialog.dismiss();

        for (Config config:(List<Config>)list) {
            apiParams.put(config.key, config.value);
            if (apiParams.get("versionCode") != null) {
                if (Integer.parseInt(apiParams.get("versionCode").toString()) > AppTools.getVersionCode(context)) {
                    SpannableStringBuilder text = new SpannableStringBuilder("\n\n" + apiParams.get("description"));
                    text.setSpan(new ForegroundColorSpan(Color.parseColor("#3C568B")), 0x4, (apiParams.get("versionName").toString().length() + 0x4), 0x21);
                    text.setSpan(new StyleSpan(0x1), 0x4, (apiParams.get("versionName").toString().length() + 0x4), 0x21);
                    customDialog.setMessage(text);
                    customDialog.show();
                }
            }
        }
        if(flag) {
            ( (BaseActivity)context).showToast(context.getString(R.string.tip_no_new_version));
        }
    }
    
    public void onFailed(Exception e) {
        progressDialog.dismiss();
    }
    
    public Map getRequestParams(String code) {
        apiParams.put("domain", "lvxin_version");
        return apiParams;
    }
    
    public void onRequest() {
        if(flag) {
            progressDialog.setMessage(context.getString(R.string.tip_loading, new Object[] {context.getString(R.string.common_detection)}));
            progressDialog.show();
        }
    }
    
    public void onLeftClick() {
        customDialog.dismiss();
    }
    
    public void onRightClick() {
        customDialog.dismiss();
        progressDialog.show();
        progressDialog.setMessage(context.getString(R.string.tip_begin_download));
        file = new File("/ichat" + apiParams.get("versionName") + ".apk");
        downloader.download(apiParams.get("url").toString(), file);
    }
    
    public void progress(String threadKey, long fileSize, long downloadSize) {
        String progress = "%";
        progressDialog.setMessage(context.getString(R.string.label_file_download, new Object[] {progress}));
        if(downloadSize == fileSize) {
            progressDialog.dismiss();
            Intent intent = new Intent("android.intent.action.VIEW");
            intent.setDataAndType(Uri.fromFile(file), "application/vnd.android.package-archive");
            intent.addFlags(0x1);
            intent.addFlags(0x10000000);
            intent.setClassName("com.android.packageinstaller", "application/vnd.android.package-archive");
            String localString1 = "com.android.packageinstaller.PackageInstallerActivity";
            context.startActivity(intent);
        }
    }
    
    public void statusChange(String threadKey, int status) {
    }
}
