/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;

public interface  CustomMessageHandler {
    
 boolean handle(Context p1, Message p2);
    
}
