/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;
import cn.cloudartisan.crius.client.constant.CIMConstant;
import cn.cloudartisan.crius.app.Global;
import cn.cloudartisan.crius.app.URLConstant;
import cn.cloudartisan.crius.bean.Bottle;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.bean.Page;
import cn.cloudartisan.crius.db.BottleDBManager;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.network.HttpAPIRequester;
import cn.cloudartisan.crius.network.HttpAPIResponser;
import cn.cloudartisan.crius.util.StringUtils;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Type700MessageHandler extends Type000MessageHandler implements CustomMessageHandler, HttpAPIResponser {
    public HashMap<String, Object> apiParams;
    HttpAPIRequester requester;
    
    public boolean handle(Context context, Message message) {
        super.handle(context, message);
        Bottle bottle = (Bottle)JSON.parseObject(JSON.parseObject(message.content).getString("bottle"), Bottle.class);
        if(bottle.sender.equals(Global.getCurrentUser().getAccount())) {
            if(BottleDBManager.getManager().queryById(bottle.gid) == null) {
                apiParams.put("gid", bottle.gid);
                requester.execute(new TypeReference<Type700MessageHandler>() {
                }.getType(), null, URLConstant.BOTTLE_DETAILED_URL);
                BottleDBManager.getManager().save(bottle);
            }
        } else if(BottleDBManager.getManager().queryById(bottle.gid) == null) {
            MessageDBManager.getManager().deleteById(message.gid);
        }
        return false;
    }
    
    public void onSuccess(Object data, List list, Page page, String code, String url) {
        if(CIMConstant.ReturnCode.CODE_200.equals(code) && data instanceof Bottle) {
            Bottle var7 = (Bottle)data;
            Message var8 = new Message();
            String var6;
            if(var7.type == 0) {
                var6 = "0";
            } else {
                var6 = "2";
            }

            var8.fileType = var6;
            var8.gid = StringUtils.getUUID();
            var8.receiver = var7.receiver;
            if(var7.type == 1) {
                var8.content = var7.length;
                var8.file = var7.content;
            } else {
                var8.content = var7.content;
            }

            var8.sender = var7.sender;
            var8.type = "700";
            var8.createTime = var7.timestamp;
            var8.status = "1";
            MessageDBManager.getManager().saveMessage(var8);
        }
    }
    
    public void onFailed(Exception e) {
    }
    
    public Map getRequestParams(String code) {
        return apiParams;
    }
    
    public void onRequest() {
    }
}
