/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.util.FileURLBuilder;
import com.nostra13.universalimageloader.core.ImageLoader;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.bean.Friend;
import android.content.Intent;
import cn.cloudartisan.crius.bean.MessageItemSource;

public class Type110MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        String account = message.content;
        String url = FileURLBuilder.getUserIconUrl(account);
        ImageLoader.getInstance().getDiskCache().remove(url);
        MessageDBManager.getManager().deleteById(message.gid);
        Friend friend = new Friend();
        friend.account = account;
        Intent intent = new Intent();
        intent.setAction("com.farsunset.cim.UPDATE_ITEM");
        intent.putExtra(MessageItemSource.class.getName(), friend);
        context.sendBroadcast(intent);
        return false;
    }
}
