/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.db.MessageDBManager;

public class Type108MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        String mid = message.content;
        MessageDBManager.getManager().updateStatus(mid, "9");
        MessageDBManager.getManager().deleteById(message.gid);
        return true;
    }
}
