/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import cn.cloudartisan.crius.bean.GroupMember;
import cn.cloudartisan.crius.db.GroupMemberDBManager;

public class Type106MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        JSONObject json = JSON.parseObject(message.content);
        GroupMember member = new GroupMember();
        member.gid = String.valueOf(System.currentTimeMillis());
        member.account = json.getString("targetUserAccount");
        member.groupId = json.getString("targetGroupId");
        member.host = "0";
        GroupMemberDBManager.getManager().saveMember(member);
        return true;
    }
}
