/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.db.GroupDBManager;
import android.content.Intent;
import cn.cloudartisan.crius.bean.ChatItem;
import cn.cloudartisan.crius.bean.Group;

public class Type107MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        String groupId = JSON.parseObject(message.content).getString("groupId");
        GroupDBManager.getManager().deleteGroup(groupId);
        Intent intent = new Intent();
        intent.setAction("com.farsunset.cim.DELETE_APPEND");
        intent.putExtra(ChatItem.NAME, (new Group(groupId)));
        context.sendBroadcast(intent);
        return true;
    }
}
