/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import android.content.Intent;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import cn.cloudartisan.crius.R;
import cn.cloudartisan.crius.bean.ChatItem;
import cn.cloudartisan.crius.bean.Friend;
import cn.cloudartisan.crius.bean.Group;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.db.GroupDBManager;
import cn.cloudartisan.crius.db.MessageDBManager;
import cn.cloudartisan.crius.message.parser.MessageParser;
import cn.cloudartisan.crius.message.parser.MessageParserFactory;

import java.util.HashMap;

public class Type103MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        JSONObject json = JSON.parseObject(message.content);
        MessageParser messageParser = MessageParserFactory.getFactory().getMessageParser(message.type);
        Group group = (Group)messageParser.decodeContent(message);
        GroupDBManager.getManager().saveGroup(group);
        Message msg = new Message();
        msg.createTime = String.valueOf(System.currentTimeMillis());
        msg.gid = String.valueOf(System.currentTimeMillis());
        msg.type = "3";
        msg.sender = group.groupId;
        msg.receiver = message.receiver;
        msg.status = "0";
        HashMap<String, Object> data = new HashMap<String, Object>();
        Friend friend = new Friend();
        friend.account = group.founder;
        friend.name = json.getString("targetUserName");
        data.put("content", context.getString(R.string.tip_group_hellow_message));
        data.put("user", friend);
        msg.content = JSON.toJSONString(data);
        MessageDBManager.getManager().saveMessage(msg);
        ChatItem chatItem = new ChatItem();
        chatItem.source = group;
        chatItem.message = msg;
        Intent intent = new Intent();
        intent.putExtra("data", chatItem);
        intent.setAction("com.farsunset.cim.MESSAGE_APPEND");
        context.sendBroadcast(intent);
        return true;
    }
}
