/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;
import cn.cloudartisan.crius.bean.Article;
import com.alibaba.fastjson.JSON;
import cn.cloudartisan.crius.db.ArticleDBManager;

public class Type800MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        Article article = (Article)JSON.parseObject(message.content, Article.class);
        ArticleDBManager.getManager().save(article);
        return true;
    }
}
