/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.message.handler;

import android.content.Context;
import cn.cloudartisan.crius.bean.Message;
import android.content.Intent;
import cn.cloudartisan.crius.ui.LoginAlertActivity;

public class Type999MessageHandler implements CustomMessageHandler {
    
    public boolean handle(Context context, Message message) {
        Intent intent = new Intent(context, LoginAlertActivity.class);
        intent.addFlags(0x10000000);
        context.startActivity(intent);
        return true;
    }
}
