/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.cloudartisan.crius.jni;

import android.content.Context;

public class JNI {
    
    public native String getAuthKey(Context p1);
    
    
    public native String getOSSAccessID(Context p1);
    
    
    public native String getOSSAccessKey(Context p1);
    
    
    static {
       // System.loadLibrary("auth");
    }
}
